(function(g){var window=this;var U4=function(a){var b={format:a.o,languageCode:a.l,languageName:a.C,displayName:g.rH(a),kind:a.A,name:a.B,id:a.ia,is_servable:a.M,is_translateable:a.F,vss_id:a.D};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},V4=function(a){return a.g?a.g.languageCode:a.l},hwa=function(a,b){var c=new g.qH;
c.l=a.l;c.C=a.C;c.B=a.B;c.A=a.A;c.F=a.F;c.D=a.D;c.H=a.H;c.g=b;return c},iwa=function(a){a=g.jd(window.document,"track",void 0,a.g);
for(var b=0;b<a.length;b++)g.Ed(a[b])},jwa=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},W4=function(a){if(!kwa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(lwa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},X4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.ZO.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.l=k},Y4=function(a,b,c,d,e){g.ZO.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},$4=function(a){a=void 0===a?{}:a;
var b="_"+Z4++;return new Y4(0,0x8000000000000,0,b,a)},a5=function(a,b,c,d,e,f){var k={};
g.Fa(k,b);g.Fa(k,a.params);g.Fa(k,c);var l={};g.Fa(l,b.kb);a.params.kb&&g.Fa(l,a.params.kb);g.Fa(l,c.kb);k.kb=l;g.X.call(this,{G:"div",L:"caption-window",T:{id:"caption-window-"+a.id,dir:1==k.Xj?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{G:"span",L:"captions-text"}]});this.o=[];this.I=!1;this.D=a;this.C=[];this.F=[];this.xa=e;this.oa=f;this.B=null;this.W=.96*e;this.da=.96*f;this.l=k;this.na=c;this.A=this.ua["captions-text"];this.fa=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.K=d/360*16;this.type=0;this.Y=this.K*mwa(l);a=new g.dF(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.bL,this);a.subscribe("dragmove",this.aL,this);a.subscribe("dragend",this.ZK,this);this.ca=this.ba=0;a="";this.l.ik&&(a=W4(this.l.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.ik+")");b={"background-color":a,display:!1===this.l.isVisible?"none":"","text-align":nwa[this.l.textAlign]};this.fa&&(b["border-radius"]=a?this.Y/
8+"px":"");g.ih(this.element,b);switch(this.l.Rg){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},mwa=function(a){var b=1+.25*(a.aj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},b5=function(a,b){var c={},d=b.background?b.background:a.l.kb.background;
if(null!=b.Ze||b.background){var e=null!=b.Ze?b.Ze:a.l.kb.Ze;d=W4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.fa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Y/8+"px")}if(null!=b.aj||null!=b.offset)c["font-size"]=a.K*mwa(b)+"px";d=1;e=b.color||a.l.kb.color;if(b.color||null!=b.Dh)e=W4(e),d=null==b.Dh?a.l.kb.Dh:b.Dh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Rh;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Yv&&
(k=e=b.Yv);var l=a.K/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.RD()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.kb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Qr&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.fr&&(c.visibility="hidden");return c},owa=function(a,b,c){a.I=a.I||!!c;
var d={};g.Fa(d,a.l.kb);g.Fa(d,c||b.l);g.Fa(d,a.na.kb);c=a.C[0];if(c&&d.background==c.background&&d.Ze==c.Ze&&!!d.fr==!!c.fr&&d.Rh==c.Rh){var e;for(e=0;e<a.C.length;e++)if(jwa(d,a.C[e])){var f=a.F[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.xd("SPAN");g.ih(f,b5(a,e));a.F[0].appendChild(f);e=1}a.F.length=e;a.C.length=e}else a.F.length=0,a.C.length=0,f=g.xd("SPAN"),g.ih(f,b5(a,d)),a.A.appendChild(f);a.B&&a.B.parentNode!=f&&(g.Ed(a.B),f.appendChild(a.B));c=(k=g.v(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.o.length||!b.C){if(0<e||0!=a.o.length){var m=g.xd("BR");f.appendChild(m)}f.appendChild(g.zd("\u00a0"));a.B=g.zd("\u00a0");f.appendChild(a.B)}l&&(m=a.B,m.parentNode&&m.parentNode.insertBefore(k?g.zd(l):l,m))}a.C.push(d);a.F.push(f);a.o.push(b)},pwa=function(){},d5=function(){this.A=this.l=this.mode=this.o=0;
this.B=new c5(this);this.C=new c5(this);this.g=[];this.clear()},rwa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Fm:a,
Gm:b,result:0};a=qwa[a];b=qwa[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{Fm:a,Gm:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Fm:a,Gm:b,result:2};return{Fm:a,Gm:b,result:3}},twa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,swa(a.B,b,c,d))},uwa=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?twa(a,d.Tv,d.Uv,b):1==d.type&&a.o&496&&swa(a.C,d.Tv,d.Uv,b)}a.g.length=0},e5=function(){this.g=0},f5=function(){this.l=this.o=this.g=0},g5=function(){this.timestamp=this.se=0;
this.g=!1},h5=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new g5}this.g=this.l=this.Fc=0;this.style=new e5;this.B=a;this.A=0},i5=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.o[m][q];
if(0!=r.se){0==c&&(c=m,d=q);n=String.fromCharCode(r.se);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.se||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.A(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.o[k][m],r=q.se,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==r)l&&b.A(c,d,e,f,l),e=f,l="",d=c=0},zwa=function(a,b){switch(a){case 0:return vwa[(b&127)-32];
case 1:return wwa[b&15];case 2:return xwa[b&31];case 3:return ywa[b&31]}return 0},j5=function(a){return a.o[a.Fc][a.l]},k5=function(a,b,c){2<=b&&1<a.l&&(--a.l,j5(a).se=0);
var d=j5(a);d.timestamp=a.B.l+0;d.se=zwa(b,c);32>a.l&&a.l++},Awa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].Xm(a.o[c+e][f])},l5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},m5=function(a){a.Fc=0<a.g?a.g:1;
a.l=1;l5(a,0,15)},n5=function(a){this.A=a;
this.B=0;this.style=new e5;this.C=new h5(a);this.D=new h5(a);this.F=new h5(a);this.l=this.C;this.o=this.D;this.g=this.l},o5=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:i5(d,c),m5(a.l),m5(a.o),d.Fc=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(i5(d,c),l5(d,d.Fc-d.g,b)):d.Fc<b&&(b=d.g),d.g=b)},Bwa=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},Cwa=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.A.mode=1<<a.g.A},c5=function(a){this.l=a;
this.g=new f5;this.B=0;this.o=new n5(a);this.C=new n5(a);this.A=this.o},swa=function(a,b,c,d){a.g.update();
b=rwa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Fm;c=b.Gm;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&k5(a,0,b),c&96&&k5(a,0,c),0!=b&&0!=c&&3==a.style.g&&i5(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.Fc;break;case 3:if(d!=c.Fc){if(d<c.g&&(d=c.g,d==c.Fc))break;var f=1+c.Fc-c.g,k=1+d-c.g;Awa(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));l5(c,b,e)}}c.Fc=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:k5(b.g,0,32);break a;case 48:57==c?(b=b.g,j5(b).se=0,32>b.l&&b.l++):k5(b.g,1,c&15)}break;case 2:c&32&&k5(b.g,2,c&31);break;case 3:c&32&&k5(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Bwa(b);break;case 33:b=
b.g;1<b.l&&(--b.l,j5(b).se=0);break;case 36:b=b.g;d=j5(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:o5(b,2,d);break;case 38:o5(b,3,d);break;case 39:o5(b,4,d);break;case 40:k5(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.F;d.g=15;d.style.set(4);m5(d);Cwa(b);break;case 43:Cwa(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:i5(a,d)}l5(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Fc){++a.Fc;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.Fc<a.g&&(a.Fc=a.g));b=a.Fc-a.g+1;i5(a,d);Awa(a,b,b+1,a.g-1);l5(a,a.Fc,1)}break;case 46:l5(b.o,0,15);break;case 47:i5(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;Bwa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},p5=function(){},q5=function(a){this.o=a;
this.l=null},Ewa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.Hr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");Dwa(d,e,k,b,f,a.firstChild,{},c)},Dwa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Qr=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");r5.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new X4(a,b,c,d,n.nodeValue,e||0<m,g.Tb(k)?void 0:k));else{var q={};g.Fa(q,k);Dwa(a,b,c,d,e||0<m,n,q,l)}}},s5=function(){this.o={};
this.l=null},t5=function(a){this.l={};
this.B={};this.C={};this.o="_"+Z4++;this.A=a},u5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},v5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},w5=function(a,b){var c=u5(a,b);
if(void 0!=c)return c},x5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return r5.test(c),c},Fwa=function(a,b){var c={},d=b.getAttribute("ws");
g.Fa(c,d?a.C[d]:a.A);d=w5(b,"mh");null!=d&&(c.hs=d);d=w5(b,"ju");null!=d&&(c.textAlign=d);d=w5(b,"pd");null!=d&&(c.Xj=d);d=x5(b,"wfc");null!=d&&(c.windowColor=d);d=u5(b,"wfo");void 0!=d&&(c.ik=d/255);return c},Gwa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Fa(c,a.B[d]);d=w5(b,"ap");null!=d&&(c.Rg=d);d=u5(b,"cc");null!=d&&(c.PG=d);d=u5(b,"ah");null!=d&&(c.mi=d);d=u5(b,"rc");null!=d&&(c.Mo=d);d=u5(b,"av");null!=d&&(c.Ki=d);return c},Hwa=function(a,b,c){var d={};
g.Fa(d,Gwa(a,b));g.Fa(d,Fwa(a,b));c?jwa(d,a.A)?(c=a.o,d=a.A):c="_"+Z4++:c=b.getAttribute("id")||"0";a=u5(b,"t");b=u5(b,"d")||0x8000000000000;return new Y4(a,b,0,c,d)},y5=function(a,b,c){this.D=c;
this.version=this.B=this.C=this.g=0;this.l=new window.DataView(a);this.o=[]},z5=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},Iwa=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},A5=function(a,b){this.o=a;
this.track="CC3"==b.C?4:0;this.l=new d5;this.l.o=1<<this.track},Kwa=function(a){if(g.v(a))return!1;
a=new y5(a,8,0);return Jwa(a)},Jwa=function(a){if(!(a.g<a.l.byteLength)||1380139777!=Iwa(a))return!1;
a.version=z5(a);if(1<a.version)return!1;z5(a);z5(a);z5(a);return!0},Lwa=function(){this.l=[];
this.g=[]},B5=function(a,b){return b?a.g.concat(a.l):a.g},C5=function(a,b){switch(b.A){case "asr":var c=a.l;
g.Ka(c,(0,g.z)(b.I,b))||c.push(b);break;default:c=a.g,g.Ka(c,(0,g.z)(b.I,b))||c.push(b)}},D5=function(){this.l=null},Mwa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Qr=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new X4(b,c,d,e.id,q.nodeValue,f||0<n,g.Tb(l)?void 0:l),m.push(q),e!=a.l&&e.l.push(q);else{var r={};g.Fa(r,l);Mwa(a,b,c,d,e,!0,q,r,m)}}},E5=function(a){var b=0;
a=g.na(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},F5=function(a){g.M.call(this);
this.gy=!!a;this.l=new Lwa;this.D=[];this.g=null},Owa=function(a){var b={};
if(a=V4(a))b.lang=a,Nwa.test(a)&&(b.Xj=1);return b},Pwa=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.v(b)){var f=new window.DataView(b);1718909296==f.getUint32(4)&&(f=g.MH(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),Kwa(b)||(b=g.Zd(new window.Uint8Array(b))))}if(g.v(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new D5),a.g.g(b,d);b=g.Hr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new t5(Owa(c)):a.g=new s5:a.g=new q5(Owa(c)));return a.g.g(b,d)}try{if(Kwa(b))return a.g||(a.g=
new A5(e,c)),a.g.g(b,d)}catch(k){g.nD(k)}return[]},G5=function(a){F5.call(this,a.Mm);
this.A=void 0;this.o=null;this.D=a.captionTranslationLanguages},H5=function(){this.qb=[]},I5=function(a,b,c,d,e,f){g.M.call(this);
this.C=b;this.A=new H5;this.g=null;this.D=d;this.I=f;this.l=this.o=null;this.K=c;this.B=e||!1;this.F=new g.Ht(this.zy,1E3,this);g.N(this,this.F);this.H=new g.ZE(this);g.N(this,this.H);this.H.O(b,"seekto",this.kz);this.kz(b.getCurrentTime());this.zy()},Qwa=function(a,b){var c=g.qJ(b,{}).Oa(),d={format:"RAW",
ad:(0,g.z)(a.OQ,a),withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.l=g.ID(c,d);a.o=b;c=a.A;d=a.o.ya[0].sa;var e=g.cb(c.qb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.qb[e-1]&&e<c.qb.length&&1==c.qb[e]-d?(g.Ra(c.qb,e),g.Ra(c.qb,e-1)):0<e&&1==d-c.qb[e-1]?c.qb[e-1]=d:e<c.qb.length&&1==c.qb[e]-d?c.qb[e]=d:(g.Ya(c.qb,e,0,d),g.Ya(c.qb,e+1,0,d)))},J5=function(a,b){F5.call(this);
this.A=a;this.B=b;this.o=null;this.C=!1},Rwa=function(a,b){if(b in a.A.g)return a.A.g[b];
if(g.PJ(a.A))for(var c in a.A.g){var d=a.A.g[c];if(g.BG(d.info.mimeType))return d}return null},Swa=function(a,b){return a.za||g.W(b).Ra&&null!=a.pa&&null!=a.pa.g.rawcc},K5=function(a,b,c,d,e,f){a5.call(this,a,b,c,d,e,f);
this.type=1},L5=function(a,b,c,d,e,f){a5.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=2;this.H=this.M=0;this.N=window.NaN;this.la=null;this.X=new g.Ht(this.SQ,433,this);g.N(this,this.X)},M5=function(a){if(!a.M){var b=g.xd("SPAN");
g.ih(b,b5(a,a.l.kb));a.A.appendChild(b);b.appendChild(g.zd("M"));var c=b.offsetHeight,d=g.xd("BR");b.appendChild(d);b.appendChild(g.zd("M"));a.M=b.offsetHeight-c;a.A.removeChild(b)}return a.M},N5=function(a,b,c,d){F5.call(this,d);
c=c||g.zD(a).hl||"";c=c.split("_").join("-");this.B=g.BD(a,{hl:c});this.A=b;this.C={};this.o=null},O5=function(a,b,c,d){var e=g.U("YTP_VIDEO_SUBTITLES_OVERRIDE"),f=new g.lZ(b,void 0,e);
g.t_.call(this,Twa(d),a,b,c,e,function(){return g.tZ(c,f)});
g.S(this.element,"ytp-subtitles-options-menu-item");this.I=d.option.toString();a=d.options;this.K=g.ib(a,this.Xz,this);this.F=f;g.N(this,this.F);b=new g.iZ({G:"div",L:"ytp-menuitemtitle",J:[g.U("YTP_VIDEO_SUBTITLES_OVERRIDE_DESC")]},0);g.N(this,b);g.mZ(this.F,b,!0);this.B=new g.iZ({G:"div",L:"ytp-menuitem",T:{role:"menuitemradio",tabindex:"0"},J:[{G:"div",L:"ytp-menuitem-label",J:[g.U("YTP_ON")]}]},-1);g.N(this,this.B);g.mZ(this.F,this.B,!0);this.O(this.B.element,"click",g.Ea(this.Yz,!0));this.l=
new g.iZ({G:"div",L:"ytp-menuitem",T:{role:"menuitemradio",tabindex:"0"},J:[{G:"div",L:"ytp-menuitem-label",J:[g.U("YTP_OFF")]}]},-2);g.N(this,this.l);g.mZ(this.F,this.l,!0);this.O(this.l.element,"click",g.Ea(this.Yz,!1));g.u_(this,(0,g.I)(a,this.Xz))},Twa=function(a){return(a.message?g.U(a.message):a.text)||""},P5=function(a,b){g.lZ.call(this,a,void 0,g.U("YTP_OPTIONS"));
this.l={};for(var c=0;c<g.IZ.length;c++){var d=g.IZ[c],e=new O5(-c,a,b,d);g.N(this,e);e.subscribe("settingChange",this.o,this);this.l[d.option.toString()]=e;g.mZ(this,e,!0)}c=new g.iZ(g.jZ(),-g.IZ.length,g.U("YTP_RESET"));g.N(this,c);c.R("click",(0,g.z)(this.o,this,"reset",!0));g.mZ(this,c,!0)},Uwa=function(a,b){for(var c in b){var d=a.l[c];
if(d){var e=b[c].toString(),f=!!b[c+"Override"];d.o[e]&&(d.qf(e),d.B.element.setAttribute("aria-checked",!f),d.l.element.setAttribute("aria-checked",f))}}},Q5=function(a,b){g.t_.call(this,g.U("YTP_AUTO_TRANSLATE"),0,a,b);
this.l={}},R5=function(a,b){var c=new P5(a,b);
g.t_.call(this,g.U("YTP_SUBTITLES"),3,a,b,g.U("YTP_OPTIONS"),function(){return g.tZ(b,c)});
this.l=a;this.B={};this.M=new g.Ht(g.Ea(this.Wz,!1),3E3,this);g.N(this,this.M);this.I=new g.X({G:"div",J:[{G:"span",J:[g.U("YTP_SUBTITLES")]},{G:"span",L:"ytp-menuitem-label-count",J:["{{content}}"]}]});g.N(this,this.I);g.hZ(this,this.I);this.F=new Q5(a,b);g.N(this,this.F);this.F.subscribe("select",this.gN,this);this.K=c;g.N(this,this.K);this.K.subscribe("settingChange",this.fN,this);this.O(a,"videodatachange",this.tl);this.O(a,"onApiChange",this.tl);this.O(a,"onCaptionsTrackListChanged",this.tl);
this.O(a,"captionschanged",this.tl);this.tl()},U5=function(a){g.nU.call(this,a);
g.lG({YTP_CLICK_FOR_SETTINGS:"Click $GEAR_ICON for settings",YTP_SAMPLE_SUBTITLES:"Captions look like this"});this.o=g.W(a);this.A=a.ea();this.na=g.NT(a);this.I=a;var b=null,c=g.KC("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.yC(c));this.ba=b;this.C={kb:{}};this.H={kb:{}};this.M=[];this.V={};this.Y={};this.N=!1;this.oa="1"==this.A.hc.cc_auto_caps||"1"==this.o.td.cc_auto_caps;this.F="3"==this.o.o&&!!a.app.B&&!!a.app.B.g.textTracks;c=b=this.l=this.da=this.B=this.D=this.K=this.X=this.la=
null;this.F||(b=new g.Et(this.WC,void 0,this),g.N(this,b),c=new g.Ht(this.CS,2E3,this),g.N(this,c));this.ca=b;this.fa=c;this.W=new g.ZE(this);g.N(this,this.W);this.F||this.W.O(a,"resize",this.mu);this.W.O(a,"onPlaybackAudioChange",this.TN);this.W.O(a,"crn_captions",this.FK,this);this.W.O(a,"crx_captions",this.GK,this);S5(this,T5(this,"display-settings")||{})},Vwa=function(a){if(a.A.captionTracks.length)var b=a.g.th().Qv;
if("FORCED_ON"==b||1==a.o.Vg||1==a.A.Vg||"alwayson"==g.nN(a.A,"yt:cc"))return!0;if(2==a.o.Vg){var c=T5(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.nN(a.A,"yt:cc")},Wwa=function(a,b){if(a.B){var c=B5(a.B.l,b||a.oa);
if(a.D&&a.D.g)return a.D.g;for(var d=[a.A.Ug,a.o.Ug,g.nN(a.A,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(V4(c[f])==d[e])return c[f];return a.D&&a.D.pq?a.D.pq:c[0]||a.D&&a.D.Ak}return null},Xwa=function(a,b){for(var c=a.I.app.B.g.textTracks,d=a.l.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},V5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.N=c);a.l=b;a.load(d)},Ywa=function(a,b){var c=g.k0(a.na,!0).height;
if(!c)return null;var d=a.na.Sa();switch(null!=b.params.hs?b.params.hs:b.params.oT?2:1<b.l.length?1:0){case 1:return new K5(b,a.C,a.H,c,d.width,d.height);case 2:return new L5(b,a.C,a.H,c,d.width,d.height);default:return new a5(b,a.C,a.H,c,d.width,d.height)}},S5=function(a,b,c){var d=W5.kb;
a.C={};g.Fa(a.C,W5);a.C.kb={};g.Fa(a.C.kb,d);a.H={kb:{}};var e=b.backgroundOverride?a.H:a.C,f=b.background||d.background;r5.test(f);e.kb.background=f;e=b.colorOverride?a.H:a.C;f=b.color||d.color;r5.test(f);e.kb.color=f;e=b.windowColorOverride?a.H:a.C;f=b.windowColor||W5.windowColor;r5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.H:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ze);e.kb.Ze=f;e=b.fontSizeIncrementOverride?a.H:a.C;f=b.fontSizeIncrement;null==f&&(f=d.aj);e.kb.aj=f;e=b.textOpacityOverride?
a.H:a.C;f=b.textOpacity;null==f&&(f=d.Dh);e.kb.Dh=f;e=b.windowOpacityOverride?a.H:a.C;f=b.windowOpacity;null==f&&(f=W5.ik);e.ik=f;e=b.charEdgeStyleOverride?a.H:a.C;f=b.charEdgeStyle;null==f&&(f=d.Rh);e.kb.Rh=f;e=b.fontFamilyOverride?a.H:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.kb.fontFamily=f;a.loaded&&a.mu();c&&X5(a,"display-settings",b)},$wa=function(a,b){if(b&&!a.K){var c=$4({Xj:0,
lang:"en"});a.K=[c,new X4(c.start,c.end-c.start,0,c.id,g.U("YTP_SAMPLE_SUBTITLES"))];g.aU(a.g,a.K)}else!b&&a.K&&(Zwa(a,a.K),a.K=null)},Zwa=function(a,b){g.cU(a.g,b);
(0,g.C)(b,function(a){g.Sa(this.M,a)},a);
a.ca.Ik()},axa=function(a,b){return a&&g.v(a)&&r5.test(a)?a:b},bxa=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},dxa=function(a,b){if(a&&g.v(a)){var c=cxa.indexOf(a);
return-1!=c?c:b}return b},fxa=function(a,b){if(a&&g.v(a)){var c=exa.indexOf(a);
return-1!=c?c:b}return b},gxa=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?g.Vc(a,-2,4):b},T5=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},X5=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.wH.prototype.An=g.da(4,function(a){return(a=this.Wh(a))?a.l:0});
g.FJ.prototype.An=g.da(3,function(){return 0});
g.qH.prototype.I=g.da(2,function(a){return a?this.toString()==a.toString():!1});
var Nwa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,lwa=/#(.)(.)(.)/,kwa=/^#(?:[0-9a-f]{3}){1,2}$/i,r5=/^#(?:[0-9a-f]{3}){1,2}$/i,exa="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),cxa=["none","raised","depressed","uniform","dropShadow"];var nwa=["left","right","center"];var W5={windowColor:"#080808",ik:0,textAlign:2,Rg:7,mi:50,Ki:100,kb:{background:"#080808",Ze:.75,Rh:0,color:"#fff",fontFamily:4,aj:0,Dh:1,offset:1}};g.p(X4,g.ZO);g.p(Y4,g.ZO);var Z4=0;g.p(a5,g.X);g.h=a5.prototype;g.h.bL=function(a,b){var c=g.yh(this.element,this.element.parentElement);this.ba=a-c.x;this.ca=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.aL=function(a,b){var c=g.Bh(this.element),d=a-this.ba-.02*this.xa,e=b-this.ca-.02*this.oa,f=(d+c.width/2)/this.W*3;f=Math.floor(g.Vc(f,0,2));var k=(e+c.height/2)/this.da*3;k=Math.floor(g.Vc(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.W;d=100*g.Vc(d,0,1);c=(e+k/2*c.height)/this.da;c=100*g.Vc(c,0,1);this.D.params.Rg=l;this.D.params.Ki=c;this.D.params.mi=d;this.l.Rg=l;this.l.Ki=c;this.l.mi=d;this.PB()};
g.h.ZK=function(){g.eq(this.element,"ytp-dragging")};
g.h.PB=function(){this.Hi(this.o)};
g.h.Sb=function(){return this.type};
g.h.Hi=function(a){var b=Math.min(this.ax(),this.W),c=this.Zw();g.ih(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Pp(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.l.mi+2,e=this.l.Rg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.l.Ki+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.ih(this.element,a)};
g.h.Pp=function(a){var b;for(b=0;b<a.length&&a[b]==this.o[b];b++);if(this.I||this.o.length>b)b=0,this.I=!1,this.o=[],this.C=[],this.F=[],this.B=null,g.Cd(this.A);for(;b<a.length;b++)owa(this,a[b])};
g.h.ax=function(){return 0};
g.h.Zw=function(){return 0};pwa.prototype.A=function(){};d5.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
d5.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var qwa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];e5.prototype.set=function(a){this.g=a};
e5.prototype.get=function(){return this.g};
f5.prototype.clear=function(){this.g=0};
f5.prototype.update=function(){this.g=2==this.g?1:0};
f5.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
g5.prototype.Xm=function(a){this.se=a.se;this.timestamp=a.timestamp;this.g=a.g};
g5.prototype.reset=function(){this.timestamp=this.se=0;this.g=!1};
h5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.se?a+"_":a+String.fromCharCode(d.se)}a+="\n"}return a};
h5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.Fc=1};
var vwa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],wwa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],xwa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],ywa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];n5.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.D;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
c5.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};p5.prototype.reset=function(){};g.p(q5,p5);q5.prototype.g=function(a){var b=[];this.l||(this.l=$4(this.o),b.push(this.l));a=g.na(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())Ewa(c.value,this.l.id,b);return b};g.p(s5,p5);
s5.prototype.g=function(a){var b=[];this.l||(this.l=$4(),this.o[this.l.id]=this.l,b.push(this.l));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.o[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=$4());
var k={};f&&(g.Fa(k,f.params),f=f.params.kb)&&(k.kb={},g.Fa(k.kb,f));e.getAttribute("rc")&&(k.Mo=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.PG=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Rg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.mi=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Ki=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Xj=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Xj=0));e.getAttribute("bc")&&(k.kb||(k.kb={}),k.kb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.kb||(k.kb={}),k.kb.Ze=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.kb||(k.kb={}),k.kb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.oT=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new Y4(c,f,0,e,k)}else c=null}this.o[d]=c;b.push(c);break;case "text":for(d=[],Ewa(a,this.l.id,d),d=g.na(d),c=d.next();!c.done;c=d.next())c=c.value,this.o[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(t5,p5);
t5.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.na(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())if(b=b.value,1==b.nodeType)switch(b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.na(c.childNodes),a=c.next();!a.done;a=c.next())if(a=a.value,1==a.nodeType)switch(a.tagName){case "pen":b=a.getAttribute("id");var e=this.l,f={},k=a.getAttribute("p");k&&g.Fa(f,this.l[k]);k=v5(a,"b");null!=k&&(f.bold=k);k=v5(a,"i");null!=k&&(f.Qr=k);k=v5(a,"u");null!=
k&&(f.underline=k);k=w5(a,"et");null!=k&&(f.Rh=k);k=w5(a,"of");null!=k&&(f.offset=k);k=x5(a,"bc");null!=k&&(f.background=k);k=x5(a,"ec");null!=k&&(f.Yv=k);k=x5(a,"fc");null!=k&&(f.color=k);k=w5(a,"fs");void 0!=k&&0!=k&&(f.fontFamily=k);k=u5(a,"sz");void 0!=k&&(f.aj=k/100-1);k=u5(a,"bo");void 0!=k&&(f.Ze=k/255);a=u5(a,"fo");void 0!=a&&(f.Dh=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.C[b]=Fwa(this,a);break;case "wp":b=a.getAttribute("id"),this.B[b]=Gwa(this,a)}c=[];if(d)for(a={},b=void 0,
d=g.na(d.childNodes),e=d.next();!e.done;e=d.next())if(e=e.value,1==e.nodeType)switch(e.tagName){case "w":var l=Hwa(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=yd;f=[];k=e.getAttribute("w")||this.o;var q=!!v5(e,"a"),r=u5(e,"t")||0,u=u5(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);m=q?6:5;n=this.l[e.getAttribute("p")];for(var B=e.childNodes,E=0;E<B.length;E++){var L=B[E];0<E&&(q=!0);var Y=void 0;1==L.nodeType&&(Y=L);if(Y&&"s"==Y.tagName){var ka=
Y;L=r;Y=u;var $a=k,ba=q,fd=m,Ff=ka.textContent?ka.textContent:"",yb=this.l[ka.getAttribute("p")];ka=u5(ka,"t")||0;L=new X4(L+ka,Y-ka,fd,$a,Ff,ba,yb)}else L=new X4(r,u,m,k,L.textContent||"",q,n);f.push(L)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var yd=null!=e.getAttribute("d");f[0].windowId==this.o&&(l=Hwa(this,e,!0),c.push(l));e=g.na(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.l.push(f),c.push(f)}}return c};g.p(y5,pwa);y5.prototype.A=function(a,b,c,d,e){if(c<d){var f="_"+Z4++;c=c/1E3-this.D;d=d/1E3-this.D;a=new Y4(c,d-c,5,f,{textAlign:0,Rg:0,mi:2.5*b,Ki:5.33*a});e=new X4(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.p(A5,p5);A5.prototype.g=function(a){a=new y5(a,a.byteLength,this.o);if(Jwa(a)){for(;a.g<a.l.byteLength;)for(0==a.version&&(a.C=Iwa(a)*(1E3/45)),a.B=z5(a);0<a.B;a.B--){var b=z5(a),c=z5(a),d=z5(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.l,b.g.push({time:a.C,type:this.track,Tv:c,Uv:d,order:b.g.length}))}uwa(this.l,a);return a.o}return[]};
A5.prototype.reset=function(){this.l.clear()};g.p(D5,p5);
D5.prototype.g=function(a,b){for(var c=[],d=a.split(hxa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!ixa.test(f)){var l=Y5.exec(f);if(l&&3<=l.length){var m=E5(l[1]);l=E5(l[2])-m;m+=k;f=f.substring(Y5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");Y5.lastIndex=0;var n=f;f={};this.l||(this.l=$4({hs:0}),c.push(this.l));var q=this.l;k=5;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new X4(m,l,k,q.id,n,!1,g.Tb(f)?void 0:f));else{n=n.split(jxa);1!=n.length&&(k=6,q="_"+kxa++,q=new Y4(m,l,k,q,{}),c.push(q));
for(var r=m,u=0;u<n.length;u++){var B=n[u];if(0==u%2){var E=g.Hr("<html>"+B+"</html>");if(E.getElementsByTagName("parsererror").length){var L=E.createElement("span");L.appendChild(E.createTextNode(B))}else L=E.firstChild;Mwa(this,r,l-(r-m),k,q,0<u,L,f,c)}else r=E5(B)}}}Y5.lastIndex=0}}return c};
var kxa=0,ixa=/^NOTE/,hxa=/(?:\r\n|\r|\n){2,}/,Y5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),jxa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(F5,g.M);F5.prototype.trackCount=function(){return B5(this.l,!0).length};
F5.prototype.Id=function(){this.g=null};
F5.prototype.U=function(){g.M.prototype.U.call(this);this.Id()};
F5.prototype.BB=function(){return!1};g.p(G5,F5);g.h=G5.prototype;g.h.Xr=function(a,b){var c=this.Gk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Id();this.o=g.ID(c,{format:"RAW",Hb:d,withCredentials:!0})};
g.h.Yr=function(a,b,c,d){this.A=c;if(d)for(b=g.na(d.captionTracks),c=b.next();!c.done;c=b.next())C5(this.l,c.value);a()};
g.h.Gk=function(a){var b=a.Oa(),c={};if(this.A||a.o)c.fmt=this.A||"srv"+a.o;a.g&&(c.tlang=a.g.languageCode);return g.BD(b,c)};
g.h.Id=function(){F5.prototype.Id.call(this);this.o&&this.o.abort()};
g.h.U=function(){this.Id();F5.prototype.U.call(this)};H5.prototype.contains=function(a){a=g.cb(this.qb,a);return 0<=a||0>a&&1==(-a-1)%2};
H5.prototype.length=function(){return this.qb.length/2};g.p(I5,g.M);g.h=I5.prototype;g.h.U=function(){g.M.prototype.U.call(this);this.l&&this.l.abort()};
g.h.kz=function(a){var b=this.g;this.g=g.Ia(this.K.eh(a).ya);b!=this.g&&this.I&&this.I()};
g.h.reset=function(){this.A=new H5;this.l&&(this.l.abort(),this.l=null)};
g.h.zy=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.ri(a);!a||this.l||this.g&&30<this.g.startTime-this.C.getCurrentTime()||(a=this.g,a=a.g.al(a),!g.W(this.C).experiments.g("disable_captions_unknown_requests")&&!a.ya[0].duration)||(this.A.contains(a.ya[0].sa)||Qwa(this,a),this.g=g.Ia(a.ya));this.F.start()};
g.h.OQ=function(a){var b=!(this.B?a.response:a.responseText)||400<=a.status;if(!g.W(this.C).experiments.g("disable_captions_redirects_redux")){var c=g.KJ(a);if(c){a=g.qJ(this.o,{});b=this.o;g.oJ(b.g,a,c);b.requestId=a.get("req_id");Qwa(this,this.o);return}}b||null===this.D||(this.B?this.D(a.response,1E3*this.o.ya[0].startTime):this.D(a.responseText,1E3*this.o.ya[0].startTime));this.l=this.o=null};g.p(J5,F5);g.h=J5.prototype;g.h.Xr=function(a,b){this.Id();var c=Rwa(this,a.l);if(c){var d=1E3*c.index.An(c.index.tg()),e=g.W(this.B).Ra;this.o=new I5(new g.YI,this.B,c,function(c,e){b(c,a,e,d)},e||g.yG(c.info),(0,g.z)(function(){e&&(this.o&&this.o.reset(),this.g&&this.g.reset(),this.C=!0)},this))}};
g.h.BB=function(){var a=this.C;this.C=!1;return a};
g.h.Yr=function(a){g.W(this.B).Ra?(C5(this.l,new g.qH({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),C5(this.l,new g.qH({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):C5(this.l,new g.qH({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Id=function(){F5.prototype.Id.call(this);this.o&&(this.o.dispose(),this.o=null)};
g.h.Gk=function(){return""};
g.h.U=function(){this.Id();F5.prototype.U.call(this)};g.p(K5,a5);K5.prototype.Pp=function(a){var b=this.D.l;a5.prototype.Pp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Fa(d,c.l);g.Fa(d,lxa);var e=c.l;var f=d}owa(this,c,d)}};
var lxa={fr:!0};g.p(L5,a5);g.h=L5.prototype;g.h.PB=function(){g.Jt(this.X)};
g.h.SQ=function(){g.eq(this.element,"ytp-rollup-mode");this.Hi(this.la,!0)};
g.h.ax=function(){return this.H};
g.h.Zw=function(){return this.D.params.Mo*M5(this)};
g.h.Hi=function(a,b){this.la=a;if(M5(this)){for(var c=0,d=0;d<this.o.length&&c<a.length;d++)this.o[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.o.concat(a.slice(c)));c=this.H;this.H=0;a5.prototype.Hi.call(this,a);this.H=Math.max(c,this.A.offsetWidth+1);c=this.D.params.Mo*M5(this)-this.A.offsetHeight;c!=this.N&&(b||(0,window.isNaN)(this.N)||(g.S(this.element,"ytp-rollup-mode"),g.It(this.X)),g.ih(this.A,"transform",c?"translateY("+c+"px)":""),this.N=c);a5.prototype.Hi.call(this,a)}else a5.prototype.Hi.call(this,
a)};g.p(N5,F5);g.h=N5.prototype;g.h.Xr=function(a,b){var c=this.Gk(a),d=(0,g.z)(function(c){this.o=null;b(c.responseText,a)},this);
this.Id();this.o=g.ID(c,{format:"RAW",Hb:d,withCredentials:!0})};
g.h.Yr=function(a,b,c){var d=this.B;b={type:"list",tlangs:1,v:this.A,fmts:Number(b||!1),vssids:1};this.gy&&(b.asrs=1);d=g.BD(d,b);b=(0,g.z)(function(b){this.o=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.l,e=g.na(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),u=m.getAttribute("kind"),B=m.getAttribute("id"),E="true"==m.getAttribute("cantran");
m=m.getAttribute("vss_id");C5(d,new g.qH({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:u,id:B,is_servable:!0,is_translateable:E,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.C[l.languageCode]=l.languageName,this.D.push(new g.pH(l))}a()},this);
this.Id();this.o=g.ID(d,{format:"RAW",Hb:b,withCredentials:!0})};
g.h.Gk=function(a){var b=this.B,c={v:this.A,type:"track",lang:a.l,name:a.B,kind:a.A,fmt:a.o};a.g&&(c.tlang=V4(a));return b=g.BD(b,c)};
g.h.Id=function(){F5.prototype.Id.call(this);this.o&&this.o.abort()};
g.h.U=function(){this.Id();F5.prototype.U.call(this)};g.p(O5,g.t_);g.h=O5.prototype;g.h.qf=function(a){g.t_.prototype.qf.call(this,a)};
g.h.Xz=function(a){return a.option.toString()};
g.h.pf=function(a){return Twa(this.K[a])};
g.h.md=function(a){g.t_.prototype.md.call(this,a);this.P("settingChange",this.I,this.K[a].option)};
g.h.Yz=function(a){this.P("settingChange",this.I+"Override",!a);this.A.Ue()};g.p(P5,g.lZ);P5.prototype.o=function(a,b){this.P("settingChange",a,b)};g.p(Q5,g.t_);Q5.prototype.B=function(a){return a.languageCode};
Q5.prototype.pf=function(a){return this.l[a].languageName||""};
Q5.prototype.md=function(a){this.P("select",a);g.uZ(this.A)};g.p(R5,g.t_);g.h=R5.prototype;g.h.Ws=function(a){return g.Tb(a)?"__off__":a.displayName};
g.h.pf=function(a){return"__off__"==a?g.U("YTP_LANGUAGE_OFF"):"__translate__"==a?g.U("YTP_AUTO_TRANSLATE"):"__contribute__"==a?g.U("YTP_CONTRIBUTE_MENU_ITEM"):("__off__"==a?{}:this.B[a]).displayName};
g.h.md=function(a){"__translate__"==a?this.F.open():"__contribute__"==a?(this.l.ld(),this.l.isFullscreen()&&g.QT(this.l),a=g.mO(g.W(this.l),this.l.ea()),g.yU(a)):(this.l.Hd("captions","track","__off__"==a?{}:this.B[a]),g.t_.prototype.md.call(this,a),this.A.Ue())};
g.h.tl=function(){var a=-1!=this.l.si().indexOf("captions"),b=this.l.ea().qk;if(a||b){if(a){var c=this.l.yc("captions","track");var d=this.l.yc("captions","tracklist",{includeAsr:!0});var e=this.l.yc("captions","translationLanguages");this.B=g.ib(d,this.Ws,this);var f=(0,g.I)(d,this.Ws);if(e.length){var k=this.F;var l=e;k.l=g.ib(l,k.B,k);g.u_(k,(0,g.I)(l,k.B));f.push("__translate__")}k=this.Ws(c)}else this.B={},f=[],k="__off__";f.unshift("__off__");this.B.__off__={};b&&f.unshift("__contribute__");
this.B[k]||(this.B[k]=c,f.push(k));g.u_(this,f);this.qf(k);a?(Uwa(this.K,this.l.ti()),this.I.Yb(d.length?" ("+d.length+")":""),this.P("size-change"),a&&e.length&&this.o.__translate__.element.setAttribute("aria-disabled",!!g.Tb(c))):(this.I.Yb(""),this.P("size-change"));this.enable(!0)}else this.enable(!1)};
g.h.Wz=function(a){this.l.Hd("captions","sampleSubtitles",a)};
g.h.gN=function(a){var b=this.l.yc("captions","track");b=g.Xb(b);b.translationLanguage=this.F.l[a];this.l.Hd("captions","track",b)};
g.h.fN=function(a,b){if("reset"==a)this.l.Ls();else{var c={};c[a]=b;this.l.po(c)}this.Wz(!0);this.M.start();Uwa(this.K,this.l.ti())};
g.h.U=function(){g.Kt(this.M);g.t_.prototype.U.call(this)};g.p(U5,g.nU);g.h=U5.prototype;g.h.U=function(){if(this.F){var a=this.I.app.B;a&&iwa(a)}else $wa(this,!1);g.nU.prototype.U.call(this)};
g.h.az=function(){return this.F?!this.A.za:this.A.captionTracks.length&&this.g.th().Ak?!0:Vwa(this)};
g.h.load=function(a){g.nU.prototype.load.call(this);this.D=this.g.th();var b=this.I.C;b&&(this.da=new R5(this.I,b));if(this.B||a)this.l?(this.F&&!this.o.experiments.g("disable_native_caption_api")?Xwa(this,!0):a?this.jB(a,this.l):3!=this.g.Qa()&&this.B.Xr(this.l,(0,g.z)(this.jB,this)),this.g.ra("captionschanged",U4(this.l))):this.g.ra("onCaptionsTrackListChanged");else{var c;Swa(this.A,this.I)?c=new J5(this.A.pa,this.g):this.A.captionTracks.length?c=new G5(this.A):c=new N5(this.A.Nm,this.A.videoId,
this.A.Ug||this.o.Ug||g.nN(this.A,"yt:cc_default_lang")||this.o.Na,this.A.Mm);this.B=c;c.Yr((0,g.z)(this.tR,this),!0,this.F?"vtt":void 0,this.g.th())}};
g.h.unload=function(){this.F?this.o.experiments.g("disable_native_caption_api")?iwa(this.I.app.B):this.l&&Xwa(this,!1):(this.fa&&g.Kt(this.fa),g.dU(this.g,"captions"),this.M=[],this.B&&this.B.Id(),this.K&&g.aU(this.g,this.K),this.mu());this.da&&(this.da.dispose(),this.da=null);g.nU.prototype.unload.call(this);var a=g.LT(this.g.app);a&&a.C&&g.qO(a.C.o);this.g.ra("captionschanged",{})};
g.h.tR=function(){if(this.N||Vwa(this))var a=Wwa(this,this.N);if(this.F){for(var b=B5(this.B.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.rH(e),srclang:V4(e),src:this.B.Gk(e),id:e.toString()};e==a&&(f["default"]=1);c.push(g.K("TRACK",f))}a=this.I.app.B;for(b=0;b<c.length;b++)a.g.appendChild(c[b]);(c=this.I.app.B.g)&&c.textTracks&&c.textTracks.addEventListener&&!this.o.experiments.g("disable_native_caption_api")&&this.W.O(c.textTracks,"change",this.uR)}else!this.l&&a&&V5(this,
a),this.g.ra("onCaptionsTrackListChanged"),this.g.ra("onApiChange")};
g.h.uR=function(){for(var a=this.I.app.B.g.textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=B5(this.B.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.l:null)!=b&&V5(this,b,!0)};
g.h.yT=function(){this.o.experiments.g("disable_native_caption_api")?this.loaded&&!this.F&&this.unload():!this.l&&this.F||this.unload()};
g.h.jB=function(a,b,c,d){if(a){this.B.BB()&&(this.M=[],g.dU(this.I,"captions"),this.ca.Ik());a=Pwa(this.B,a,b,c,d);g.aU(this.g,a);if(this.N&&(a={trackName:b.B,trackKind:b.A,trackLangCode:V4(b)},b.g&&(a.fromLangCode=b.l),g.UT(this.g,"cc",a),this.l!=(this.D&&this.D.Ak))){!this.N||g.pL(this.o)||g.FL(this.o)||(g.Kt(this.fa),b=$4({Rg:0,mi:5,Ki:5,Mo:2,textAlign:0,Xj:0,lang:"en"}),this.X=[b],a=g.U("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON"),this.la||(c=new g.qU(g.bV()),g.N(this,c),this.la=c.element),c=
b.end-b.start,(d=g.rH(this.l))&&this.X.push(new X4(b.start,c,0,b.id,d)),this.X.push(new X4(b.start,c,0,b.id,a[0]),new X4(b.start,c,0,b.id,this.la,!0),new X4(b.start,c,0,b.id,a[1],!0)),g.aU(this.g,this.X),g.It(this.fa));if(this.N||g.pL(this.o))X5(this,"module-enabled",!0),this.D&&(this.D.g=this.l);(b=g.LT(this.g.app))&&b.C&&g.qO(b.C.o)}this.N=!1}};
g.h.FK=function(a){this.M.push(a);this.ca.Ik()};
g.h.GK=function(a){g.Sa(this.M,a);var b=Swa(this.A,this.I)&&this.o.Ra;!this.o.experiments.g("disable_remove_displayed_close_caption_cue")&&b&&g.cU(this.g,[a]);this.ca.Ik()};
g.h.oS=function(a){if(a instanceof Y4){var b=this.V[a.id];b&&b.D!=a&&(b.dispose(),delete this.V[a.id],b=null);b||(b=Ywa(this,a))&&(this.V[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.CS=function(){Zwa(this,this.X);this.X=null};
g.h.WC=function(){this.ca.stop();g.Ub(this.Y);this.M.sort(g.aP);var a=this.M;if(this.K){var b=(0,g.Gd)(a,function(a){return-1==this.K.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.oS,this);g.Hb(this.V,function(a,b){this.Y[b]?(a.element.parentNode||g.hU(this.g,a.element,4),a.Hi(this.Y[b])):(a.dispose(),delete this.V[b])},this)};
g.h.OB=function(){S5(this,{},!0)};
g.h.Iq=function(){var a=W5.kb;a={background:a.background,backgroundOpacity:a.Ze,charEdgeStyle:a.Rh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.aj,textOpacity:a.Dh,windowColor:W5.windowColor,windowOpacity:W5.ik};var b=T5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.pu=function(a,b){var c={};g.Fa(c,T5(this,"display-settings"));g.Fa(c,a);S5(this,c,b);this.g.P("captionssettingschanged")};
g.h.mu=function(){!this.F&&this.loaded&&(g.Hb(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.WC())};
g.h.ws=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Vc(b,-2,4);this.pu({fontSizeIncrement:c});return c;case "reload":b&&!this.F&&V5(this,this.l,!0);break;case "stickyLoading":void 0!=b&&this.o.Gb&&X5(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.F)break;if(!g.Ba(b))break;if(g.Tb(b)){V5(this,null,!0);break}for(var d=B5(this.B.l,!0),e=0;e<d.length;e++){var f=d[e];f.l!=b.languageCode||c&&f.C!=b.languageName||(c=b.translationLanguage?hwa(f,
b.translationLanguage):f)}!c||c==this.l&&this.loaded||V5(this,c,!0)}else return this.loaded&&this.l&&this.l!=(this.D&&this.D.Ak)?U4(this.l):{};return"";case "tracklist":return this.B?(0,g.I)(B5(this.B.l,!(!b||!b.includeAsr)),function(a){return U4(a)}):[];
case "translationLanguages":return this.B?this.B.D:[];case "displaySettings":c=this.Iq();if(g.pL(this.o)&&b&&g.Ba(b))if(b.reset)this.OB();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=axa(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=bxa(b[d],c[d]);break;case "charEdgeStyle":f[d]=dxa(b[d],c[d]);break;case "fontSizeIncrement":f[d]=gxa(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=fxa(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.pu(f,!0);c=this.Iq()}c.fontFamilyOption=exa[c.fontFamily];c.charEdgeStyle=cxa[c.charEdgeStyle];return c;case "sampleSubtitles":this.F||void 0==b||$wa(this,!!b);break;case "xmlTrack":b&&this.o.Gb&&(this.F||V5(this,new g.qH({languageName:b.name}),!1,b.xml))}};
g.h.DK=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.o.Gb&&a.push("stickyLoading","xmlTrack");return a};
g.h.EK=function(){var a=this.l;return a?{cc:a.D}:{}};
g.h.GC=function(){this.loaded&&this.l?(X5(this,"module-enabled",!1),this.unload()):V5(this,this.l||Wwa(this,!0),!0)};
g.h.TN=function(){this.A.captionTracks.length&&(this.loaded&&this.unload(),this.az()&&this.load())};g.$_.captions=U5;})(_yt_player);
