(function(g){var window=this;var Sxa=function(a,b){return g.Qb(a,b)},I6=function(a){g.rm(a,"zx",g.vb());
return a},J6=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.um(a.g,b,c)},Txa=function(a,b){var c=[];
g.ck(b,function(a){try{var b=g.EC.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.DC(b)&&c.push(a):c.push(a)},a);
return c},Uxa=function(a,b){var c=Txa(a,b);
(0,g.C)(c,function(a){g.EC.prototype.remove.call(this,a)},a)},Vxa=function(){var a=g.bG;
Uxa(a,a.g.ae(!0))},Wxa=function(a,b,c,d){var e=new g.im(null,void 0);
a&&g.jm(e,a);b&&g.km(e,b);c&&g.lm(e,c);d&&g.mm(e,d);return e},Xxa=function(a){g.lF[a]&&(a=g.lF[a],(0,g.C)(a,function(a){g.jF[a]&&delete g.jF[a]}),a.length=0)},Yxa=function(a){var b=g.iF();
if(b)if(b.clear(a),a)Xxa(a);else for(var c in g.lF)Xxa(c)},K6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.cm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Zxa(this,a.capabilities||""),$xa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Zxa=function(a,b){a.capabilities.clear();
(0,g.Gd)(b.split(","),g.Ea(Sxa,aya)).forEach(function(b){a.capabilities.add(b)})},$xa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},L6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},M6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},bya=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},cya=function(a){return new L6(a)},dya=function(a){return g.ya(a)?(0,g.I)(a,cya):[]},N6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},O6=function(a){return g.ya(a)?"["+(0,g.I)(a,N6).join(",")+"]":"null"},P6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},eya=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},Q6=function(a,b){return g.Ka(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},R6=function(a,b){return g.Ka(a,function(a){return M6(a,b)})},S6=function(){var a=g.eG("yt-remote-connected-devices")||[];
g.eb(a);return a},fya=function(a){if(g.Oa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},gya=function(a){g.dG("yt-remote-connected-devices",a,86400)},U6=function(){if(T6)return T6;
var a=g.eG("yt-remote-device-id");a||(a=P6(),g.dG("yt-remote-device-id",a,31536E3));for(var b=S6(),c=1,d=a;g.D(b,d);)c++,d=a+"#"+c;return T6=d},V6=function(){var a=S6(),b=U6();
g.D(a,b);g.jG()&&g.gb(a,b);a=fya(a);if(g.Oa(a))try{g.hG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.iG("remote_sid",a.join(","),-1)}catch(c){}},hya=function(){return g.eG("yt-remote-session-browser-channel")},iya=function(){return g.eG("yt-remote-local-screens")||[]},jya=function(){g.dG("yt-remote-lounge-token-expiration",!0,86400)},kya=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(iya(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.Rl)(c,function(a){return!g.D(b,a)})&&jya();
g.dG("yt-remote-local-screens",a,31536E3)},lya=function(a,b){g.dG("yt-remote-session-browser-channel",a);
g.dG("yt-remote-session-screen-id",b);var c=S6(),d=U6();g.D(c,d)||c.push(d);gya(c);V6()},W6=function(a){a||(g.fG("yt-remote-session-screen-id"),g.fG("yt-remote-session-video-id"));
V6();a=S6();g.Sa(a,U6());gya(a)},mya=function(){if(!X6){var a=g.KC();
a&&(X6=new g.yC(a))}return X6?!!X6.get("yt-remote-use-staging-server"):!1},nya=function(){var a=window.document.createElement("a");
g.Sc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ab(a)},oya=function(a,b){var c=g.xd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Tc(c,g.Xd("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},pya=function(){var a=nya(),b=window.document.getElementById(a),c=b&&g.xE(b,"loaded");
c||b&&!c||(b=oya(a,function(){g.xE(b,"loaded")||(g.wE(b,"loaded","true"),g.pF(a),g.sD(g.Ea(Yxa,a),0))}))},Y6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},qya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Z6=function(a){a.length?rya(a.shift(),function(){Z6(a)}):$6()},sya=function(a){return"chrome-extension://"+a+a7},rya=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},b7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},$6=function(){var a=qya();
a&&a(!1,"No cast extension found")},c7=function(){if(tya){var a=2,b=qya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;rya("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",$6,c)}},uya=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(c7(),a({command:"cast.sender.init"}))},vya=function(){c7();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);Z6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+a7,"//www.gstatic.com/eureka/clank"+a7])},d7=function(a,b,c){g.M.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.sc=b;this.B=(0,g.z)(this.yH,this);this.g=!1;this.l=0;this.o=this.va=null;this.A=[]},e7=function(){},f7=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.ym(this);this.l=new g.lg;this.l.setInterval(250)},xya=function(a,b,c){a.kj=1;
a.hh=I6(b.clone());a.Di=c;a.C=!0;wya(a,null)},g7=function(a,b,c,d,e){a.kj=1;
a.hh=I6(b.clone());a.Di=null;a.C=c;e&&(a.UB=!1);wya(a,d)},wya=function(a,b){a.Nj=(0,g.H)();
h7(a);a.Ah=a.hh.clone();J6(a.Ah,"t",a.D);a.Ll=0;a.Lc=a.g.nq(a.g.Fl()?b:null);0<a.Sq&&(a.Fo=new g.Fk((0,g.z)(a.hD,a,a.Lc),a.Sq));a.A.R(a.Lc,"readystatechange",a.uS);var c=a.ci?g.Xb(a.ci):{};a.Di?(a.np="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Lc.send(a.Ah,a.np,a.Di,c)):(a.np="GET",a.UB&&!g.td&&(c.Connection="close"),a.Lc.send(a.Ah,a.np,null,c));a.g.rf(1)},Aya=function(a,b,c){for(var d=!0;!a.Oh&&a.Ll<c.length;){var e=yya(a,c);
if(e==i7){4==b&&(a.ih=4,j7(15),d=!1);break}else if(e==zya){a.ih=4;j7(16);d=!1;break}else k7(a,e)}4==b&&0==c.length&&(a.ih=1,j7(17),d=!1);a.vf=a.vf&&d;d||(l7(a),m7(a))},yya=function(a,b){var c=a.Ll,d=b.indexOf("\n",c);
if(-1==d)return i7;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return zya;d+=1;if(d+c>b.length)return i7;var e=b.substr(d,c);a.Ll=d+c;return e},Cya=function(a,b){a.Nj=(0,g.H)();
h7(a);var c=b?window.location.hostname:"";a.Ah=a.hh.clone();g.rm(a.Ah,"DOMAIN",c);g.rm(a.Ah,"t",a.D);try{a.wf=new window.ActiveXObject("htmlfile")}catch(n){l7(a);a.ih=7;j7(22);m7(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in n7)k=n7[l];else if(l in Bya)k=n7[l]=Bya[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=n7[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Uc(g.rc("b/12014412"),d);a.wf.open();a.wf.write(g.Mc(c));a.wf.close();a.wf.parentWindow.m=(0,g.z)(a.yR,a);a.wf.parentWindow.d=(0,g.z)(a.kB,a,!0);a.wf.parentWindow.rpcClose=(0,g.z)(a.kB,a,!1);c=a.wf.createElement("DIV");a.wf.parentWindow.document.body.appendChild(c);d=g.Dc(a.Ah.toString());d=g.ob(g.Ac(d));d=g.Uc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Mc(d);
a.g.rf(1)},h7=function(a){a.Cu=(0,g.H)()+a.B;
Dya(a,a.B)},Dya=function(a,b){if(null!=a.hk)throw Error("WatchDog timer not null");
a.hk=o7((0,g.z)(a.QR,a),b)},p7=function(a){a.hk&&(g.w.clearTimeout(a.hk),a.hk=null)},m7=function(a){a.g.vx()||a.Oh||a.g.vo(a)},l7=function(a){p7(a);
g.Te(a.Fo);a.Fo=null;a.l.stop();g.Em(a.A);if(a.Lc){var b=a.Lc;a.Lc=null;b.abort();b.dispose()}a.wf&&(a.wf=null)},k7=function(a,b){try{a.g.dB(a,b),a.g.rf(4)}catch(c){}},Fya=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Eya(a,b,function(e){e?c(!0):g.w.setTimeout(function(){Fya(a,b,c,d,f)},f)})}},Eya=function(a,b,c){var d=new window.Image;
d.onload=function(){try{q7(d),c(!0)}catch(e){}};
d.onerror=function(){try{q7(d),c(!1)}catch(e){}};
d.onabort=function(){try{q7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{q7(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},q7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Gya=function(a){this.g=a;
this.l=new e7},Hya=function(a){var b=r7(a.g,a.lk,"/mail/images/cleardot.gif");
I6(b);Fya(b.toString(),5E3,(0,g.z)(a.KG,a),3,2E3);a.rf(1)},t7=function(a){var b=a.g.H;
if(null!=b)j7(5),b?(j7(11),s7(a.g,a,!1)):(j7(12),s7(a.g,a,!0));else if(a.qe=new f7(a,void 0,void 0,void 0),a.qe.ci=a.Pq,b=a.g,b=r7(b,b.Fl()?a.Lk:null,a.Rq),j7(5),!g.rd||g.nc(10))J6(b,"TYPE","xmlhttp"),g7(a.qe,b,!1,a.Lk,!1);else{J6(b,"TYPE","html");var c=a.qe;a=!!a.Lk;c.kj=3;c.hh=I6(b.clone());Cya(c,a)}},u7=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new e7;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},Iya=function(a,b){this.g=a;
this.map=b;this.context=null},Jya=function(a){g.Ve.call(this,"statevent",a)},Kya=function(a,b){g.Ve.call(this,"timingevent",a);
this.size=b},Lya=function(a){g.Ve.call(this,"serverreachability",a)},Oya=function(a){Mya(a);
if(3==a.g){var b=a.ul++,c=a.qn.clone();g.rm(c,"SID",a.o);g.rm(c,"RID",b);g.rm(c,"TYPE","terminate");v7(a,c);b=new f7(a,a.o,b,void 0);b.kj=2;b.hh=I6(c.clone());(new window.Image).src=b.hh;b.Nj=(0,g.H)();h7(b)}Nya(a)},Pya=function(a){a.fH(1,0);
a.qn=r7(a,null,a.Oq);w7(a)},Mya=function(a){a.Wg&&(a.Wg.abort(),a.Wg=null);
a.oc&&(a.oc.cancel(),a.oc=null);a.pg&&(g.w.clearTimeout(a.pg),a.pg=null);x7(a);a.Pd&&(a.Pd.cancel(),a.Pd=null);a.Yg&&(g.w.clearTimeout(a.Yg),a.Yg=null)},Qya=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new Iya(a.vN++,b));2!=a.g&&3!=a.g||w7(a)},w7=function(a){a.Pd||a.Yg||(a.Yg=o7((0,g.z)(a.iB,a),0),a.cj=0)},Sya=function(a,b){if(1==a.g){if(!b){a.ul=Math.floor(1E5*Math.random());
var c=a.ul++,d=new f7(a,"",c,void 0);d.ci=null;var e=y7(a),f=a.qn.clone();g.rm(f,"RID",c);g.rm(f,"CVER","1");v7(a,f);xya(d,f,e);a.Pd=d;a.g=2}}else 3==a.g&&(b?Rya(a,b):0==a.l.length||a.Pd||Rya(a))},Rya=function(a,b){if(b)if(6<a.Qh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.ul-1;var d=y7(a)}else c=b.F,d=b.Di;else c=a.ul++,d=y7(a);var e=a.qn.clone();g.rm(e,"SID",a.o);g.rm(e,"RID",c);g.rm(e,"AID",a.wj);v7(a,e);c=new f7(a,a.o,c,a.cj+1);c.ci=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Pd=c;xya(c,e,d)},v7=function(a,b){if(a.kd){var c=a.kd.Vw();
c&&g.Hb(c,function(a,c){g.rm(b,c,a)})}},y7=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Qh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Qh?e:f-d;try{g.Hb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},Tya=function(a){a.oc||a.pg||(a.D=1,a.pg=o7((0,g.z)(a.hB,a),0),a.Ti=0)},z7=function(a){if(a.oc||a.pg||3<=a.Ti)return!1;
a.D++;a.pg=o7((0,g.z)(a.hB,a),Uya(a,a.Ti));a.Ti++;return!0},s7=function(a,b,c){a.mp=c;
a.gf=b.wg;a.C||Pya(a)},x7=function(a){null!=a.Sh&&(g.w.clearTimeout(a.Sh),a.Sh=null)},Uya=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},A7=function(a,b){if(2==b||9==b){var c=null;
a.kd&&(c=null);var d=(0,g.z)(a.nT,a);c||(c=new g.im("//www.google.com/images/cleardot.gif"),I6(c));Eya(c.toString(),1E4,d)}else j7(2);Vya(a,b)},Vya=function(a,b){a.g=0;
a.kd&&a.kd.Vv(b);Nya(a);Mya(a)},Nya=function(a){a.g=0;
a.gf=-1;if(a.kd)if(0==a.A.length&&0==a.l.length)a.kd.bq();else{g.Va(a.A);var b=g.Va(a.l);a.A.length=0;a.l.length=0;a.kd.bq(b)}},r7=function(a,b,c){var d=g.sm(c);
if(""!=d.l)b&&g.km(d,b+"."+d.l),g.lm(d,d.B);else{var e=window.location;d=Wxa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.yk&&g.Hb(a.yk,function(a,b){g.rm(d,b,a)});
g.rm(d,"VER",a.Qh);v7(a,d);return d},o7=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},j7=function(a){B7.dispatchEvent(new Jya(B7,a))},Wya=function(){},Xya=function(a,b){this.action=a;
this.params=b||{}},D7=function(a,b){g.M.call(this);
this.g=new g.Ht(this.o,0,this);g.N(this,this.g);this.l=this.sc=0;if(g.Aa(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a;C7(this)},C7=function(a){a.g.stop();
a.sc=5E3+2E4*Math.random()},E7=function(a,b,c){this.K=a;
this.C=b;this.o=new g.xC;this.l=new D7(this.XT,this);this.g=this.Za=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.M=c||!1},Yya=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.mp,sessionId:a.g.o,arrayId:a.g.wj}},Zya=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&Sya(a.g),Oya(a.g));a.F=0},F7=function(a){return!!a.g&&3==a.g.g},$ya=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},G7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Bg(a)||"";b&&(this.port=":"+b);this.domain=g.Ag(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zb(a,"10.0")&&(this.l=!1))},H7=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Kg(c+b,{})},I7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Hb:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),nd:g.Ea(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.ID(b,a)},dza=function(){var a=aza;
bza();J7.push(a);cza(J7)},K7=function(a,b){bza();
var c=J7,d=eza(a,String(b));g.Oa(c)?fza(d):(cza(c),(0,g.C)(c,function(a){a(d)}))},bza=function(){J7||(J7=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",J7,void 0))},fza=function(a){var b=(L7+1)%50;
L7=b;M7[b]=a;N7||(N7=49==b)},cza=function(a){var b=M7;
if(b[0]){var c=L7,d=N7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
M7=Array(50);L7=-1;N7=!1}},eza=function(a,b){var c=((0,g.H)()-gza)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},O7=function(a){g.bF.call(this);
this.D=a;this.g=[]},hza=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},iza=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Gd)(a.g,function(a){return!!Q6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=hza(a,b[d])||c;return c},jza=function(a,b){var c=a.g.length;
a.g=(0,g.Gd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},P7=function(a,b,c,d){g.bF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.va=window.NaN},R7=function(a){O7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;Q7(this);this.info("Initializing with "+O6(this.g))},kza=function(a){if(a.g.length){var b=(0,g.I)(a.g,function(a){return a.id}),c=H7(a.o,"/pairing/get_lounge_token_batch");
I7(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.KH,a),(0,g.z)(a.JH,a))}},Q7=function(a){var b=dya(iya());
b=(0,g.Gd)(b,function(a){return!a.uuid});
return iza(a,b)},S7=function(a,b){kya((0,g.I)(a.g,bya));
b&&jya()},U7=function(a,b){g.bF.call(this);
this.C=b;var c=g.eG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.D(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;T7("Initialized with "+g.sg(this.g))},lza=function(a,b,c){var d=H7(a.B,"/pairing/get_screen_availability");
I7(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},V7=function(a,b){a:if(g.Lb(b)!=g.Lb(a.g))var c=!1;
else{c=g.Nb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(T7("Updated online screens: "+g.sg(a.g)),a.g=b,a.P("screenChange"));mza(a)},W7=function(a){(0,window.isNaN)(a.o)||g.uD(a.o);
a.o=g.sD((0,g.z)(a.Mt,a),0<a.A&&a.A<(0,g.H)()?2E4:1E4)},T7=function(a){K7("OnlineScreenService",a)},nza=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.Zb("Requesting availability of screen w/o lounge token.")});
return b},mza=function(a){a=g.Nb(g.Ib(a.g,function(a){return a}));
g.eb(a);a.length?g.dG("yt-remote-online-screen-ids",a.join(","),60):g.fG("yt-remote-online-screen-ids")},X7=function(a){O7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};oza(this)},qza=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ie();if(k=(c?R6(k,c):null)||R6(k,b)){k.uuid=b;var l=Y7(a,k);lza(a.l,l,function(a){e(a?l:null)})}else c?pza(a,c,(0,g.z)(function(a){var f=Y7(this,new L6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));lza(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},rza=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},pza=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,Hb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.ID(H7(a.C,"/pairing/get_lounge_token_batch"),e)},sza=function(a){a.g=a.o.ie();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+O6(a.g))},oza=function(a){Z7(a);
a.o=new R7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.aI,a));sza(a);a.A=dya(g.eG("yt-remote-automatic-screen-cache")||[]);Z7(a);a.info("Initializing automatic screens: "+O6(a.A));a.l=new U7(a.C,(0,g.z)(a.ie,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.P("onlineScreenChange")},a))},Y7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=R6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.dG("yt-remote-automatic-screen-cache",(0,g.I)(a.A,bya)));Z7(a);a.B[b.uuid]=b.id;g.dG("yt-remote-device-id-map",a.B,31536E3);return b},Z7=function(a){a.B=g.eG("yt-remote-device-id-map")||{}},$7=function(a,b,c){g.bF.call(this);
this.M=c;this.H=a;this.l=b;this.o=null},a8=function(a,b){K7(a.M,b)},b8=function(a,b){$7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.eU,this);this.B=(0,g.z)(this.aS,this);this.A=g.sD((0,g.z)(function(){tza(this,null)},this),12E4)},uza=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.sg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){a8(this,"Failed to send message: getMdxSessionStatus.")},a)):a8(a,"Sending yt message without session: "+g.sg(b))},tza=function(a,b){g.uD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.wo,a),d=(0,g.z)(a.oe,a);a.kx(b,c,d,5)}}else a.oe(Error("Waiting for session status timed out."))},c8=function(a,b,c){$7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.hU,this);this.g=g.y},vza=function(a){a.g=a.H.nD(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.wo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.oe(a)},a))},wza=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}mya()&&(b.env_useStageMdx=1);return g.Ig(b)},d8=function(a,b){$7.call(this,a,b,"ManualSession");
this.g=g.sD((0,g.z)(this.xj,this,null),150)},e8=function(a,b,c,d){g.bF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.GQ,this)},xza=function(a,b){return b?g.Ka(a.o,function(a){return M6(b,a.label)},a):null},f8=function(a){K7("Controller",a)},aza=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},g8=function(a){return a.B||!!a.o.length||!!a.g},h8=function(a,b,c){b!=a.g&&(g.Te(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.fB,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.xj(null)):a.P("yt-remote-cast2-session-change",null))},yza=function(a){var b=a.l.mD(),c=a.g&&a.g.l;
a=(0,g.I)(b,function(a){c&&M6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=xza(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Eza=function(a,b,c,d,e,f,k){zza()?Aza(b,e,f,k)&&(j8(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Bza(a,c):(window.__onGCastApiAvailable=function(b,d){b?Bza(a,c):(k8("Failed to load cast API: "+d),l8(!1),j8(!1),g.fG("yt-remote-cast-available"),g.fG("yt-remote-cast-receiver"),Cza(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):pya():b7("CriOS")?uya():b7("Android")&&b7("Chrome/")&&window.navigator.presentation?vya():window.chrome&&window.navigator.presentation&&!b7("Edge")?(c7(),Z6(Dza.map(sya))):$6())):i8("Cannot initialize because not running Chrome")},Cza=function(){i8("dispose");
var a=m8();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);Fza(!1);g.nF(n8);n8.length=0},o8=function(){return!!g.eG("yt-remote-cast-installed")},Gza=function(){var a=g.eG("yt-remote-cast-receiver");
return a?a.friendlyName:null},Hza=function(){i8("clearCurrentReceiver");
g.fG("yt-remote-cast-receiver")},Iza=function(){return o8()?m8()?m8().getCastSession():(k8("getCastSelector: Cast is not initialized."),null):(k8("getCastSelector: Cast API is not installed!"),null)},q8=function(){o8()?m8()?p8()?(i8("Requesting cast selector."),m8().requestSession()):(i8("Wait for cast API to be ready to request the session."),n8.push(g.mF("yt-remote-cast2-api-ready",q8))):k8("requestCastSelector: Cast is not initialized."):k8("requestCastSelector: Cast API is not installed!")},r8=
function(a,b){p8()?m8().setConnectedScreenStatus(a,b):k8("setConnectedScreenStatus called before ready.")},zza=function(){var a=0<=g.Fb.search(/ (CrMo|Chrome|CriOS)\//);
return g.WI||a},Jza=function(a,b){m8().init(a,b)},Aza=function(a,b,c,d){var e=!1;
m8()||(a=new e8(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.dG("yt-remote-cast-available",a);g.qF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){i8("onReceiverSelected: "+a.friendlyName);
g.dG("yt-remote-cast-receiver",a);g.qF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){i8("onReceiverResumed: "+a.friendlyName);
g.dG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){i8("onSessionChange: "+N6(a));
a||g.fG("yt-remote-cast-receiver");g.qF("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
i8("cloudview.createSingleton_: "+e);return e},m8=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Bza=function(a,b){l8(!0);
j8(!1);Jza(a,function(a){a?(Fza(!0),g.pF("yt-remote-cast2-api-ready")):(k8("Failed to initialize cast API."),l8(!1),g.fG("yt-remote-cast-available"),g.fG("yt-remote-cast-receiver"),Cza());b(a)})},i8=function(a){K7("cloudview",a)},k8=function(a){K7("cloudview",a)},l8=function(a){i8("setCastInstalled_ "+a);
g.dG("yt-remote-cast-installed",a)},p8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},Fza=function(a){i8("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},j8=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},s8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Kf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},t8=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Kf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.H)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},u8=function(a){return a.ob()?((0,g.H)()-a.D)/1E3:0},v8=function(a,b){a.F=b;
a.D=(0,g.H)()},w8=function(a){switch(a.g){case 1:case 1081:return((0,g.H)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},x8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&t8(a)},y8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Yb(a.l);b.hasPrevious=a.Kf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},A8=function(a,b){g.bF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.OB;this.o=this.l=null;this.H=(0,g.z)(this.eO,this);this.D=(0,g.z)(this.wl,this);this.F=(0,g.z)(this.dO,this);this.I=(0,g.z)(this.rO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Iu,this),Kza(this))):c=3;0!=c&&(b?this.Iu(c):g.sD((0,g.z)(function(){this.Iu(c)},this),0));
var d=Iza();d&&z8(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},B8=function(a){return new s8(a.A.getPlayerContextData())},Kza=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.CQ,a),this))},a)},Lza=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},C8=function(a,b){50>a.B.Ic()&&g.QB(a.B,b)},E8=function(a,b,c){var d=B8(a);
v8(d,c);-1E3!=d.g&&(d.g=b);D8(a,d)},F8=function(a,b,c){a.A.sendMessage(b,c)},D8=function(a,b){Lza(a);
a.A.setPlayerContextData(y8(b));Kza(a)},z8=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.wl(null));
a.o=b;a.o&&(K7("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.wl(a.o.media[0]))},Mza=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=B8(a);b.contentId!=d.videoId&&K7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;v8(d,a.l.getEstimatedTime());D8(a,d)}else K7("CP","No cast media video. Ignoring state update.")},G8=function(a,b,c){return(0,g.z)(function(a){this.Zb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Zb("Retrying "+b+" using MDx browser channel."),F8(this,b,c))},a)},H8=function(a,b,c){g.bF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.M=window.NaN;this.V=[];this.A=this.D=this.o=this.bb=this.g=null;this.na=a;this.V.push(g.ME(window,"beforeunload",(0,g.z)(this.BH,this)));this.l=[];this.bb=new s8;this.X=b.id;this.g=Nza(this,c);this.g.subscribe("handlerOpened",this.iO,this);this.g.subscribe("handlerClosed",this.fO,this);this.g.subscribe("handlerError",this.gO,this);this.g.subscribe("handlerMessage",this.hO,this);$ya(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.bb.videoId;g.jG()&&g.dG("yt-remote-session-video-id",a)},this)},I8=function(a){K7("conn",a)},Nza=function(a,b){return new E7(H7(a.na,"/bc"),b)},J8=function(a,b){a.P("proxyStateChange",b)},Oza=function(a){a.B=g.sD((0,g.z)(function(){I8("Connecting timeout");
this.C(1)},a),2E4)},K8=function(a){g.uD(a.B);
a.B=window.NaN},L8=function(a){g.uD(a.M);
a.M=window.NaN},Pza=function(a){M8(a);
a.K=g.sD((0,g.z)(function(){N8(this,"getNowPlaying")},a),2E4)},M8=function(a){g.uD(a.K);
a.K=window.NaN},Rza=function(a,b){b&&(K8(a),L8(a));
b==(F7(a.g)&&(0,window.isNaN)(a.B))?b&&(J8(a,1),N8(a,"getSubtitlesTrack")):b?(a.W()&&a.bb.reset(),J8(a,1),N8(a,"getNowPlaying"),Qza(a)):a.C(1)},Sza=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.bb.videoId&&(g.Tb(b.params)?a.bb.l=null:a.bb.l=b.params,a.P("remotePlayerChange"))},Tza=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.bb.listId=b.params.listId||a.bb.listId;x8(a.bb,c,d);a.P("remoteQueueChange")},Vza=function(a,b){b.params=b.params||{};
Tza(a,b);Uza(a,b);a.P("autoplayDismissed")},Uza=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
v8(a.bb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.bb.g&&(c=-1E3);a.bb.g=c;c=Number(b.params.loadedTime);a.bb.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.bb.H=(0,window.isNaN)(c)?0:c;c=a.bb;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.bb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.bb.g?Pza(a):M8(a);
a.P("remotePlayerChange")},Wza=function(a,b){if(-1E3!=a.bb.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.bb.g=c;c=(0,window.parseInt)(b.params.currentTime,10);v8(a.bb,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},Xza=function(a,b){var c="true"==b.params.muted;
a.bb.volume=(0,window.parseInt)(b.params.volume,10);a.bb.muted=c;a.P("remotePlayerChange")},Yza=function(a,b){a.D=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},Zza=function(a,b){var c="true"==b.params.hasNext;
a.bb.Kf="true"==b.params.hasPrevious;a.bb.hasNext=c;a.P("previousNextChange")},Qza=function(a){g.uD(a.I);
a.I=g.sD((0,g.z)(a.C,a,1),864E5)},N8=function(a,b,c){c?I8("Sending: action="+b+", params="+g.sg(c)):I8("Sending: action="+b);
a.g.sendMessage(b,c)},O8=function(a){O7.call(this,"ScreenServiceProxy");
this.Xc=a;this.l=[];this.l.push(this.Xc.$_s("screenChange",(0,g.z)(this.cU,this)));this.l.push(this.Xc.$_s("onlineScreenChange",(0,g.z)(this.dQ,this)))},dAa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.mD("MDX_CONFIG")||b;g.bG&&Vxa();V6();P8||(P8=new G7(b?b.loungeApiHost:void 0),mya()&&(P8.g="/api/loungedev"));Q8||(Q8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",Q8,void 0));$za();var c=R8();if(!c){var d=new X7(P8);g.va("yt.mdx.remote.screenService_",d,void 0);c=R8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Eza(a,d,function(a){a?S8()&&r8(S8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.qF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),T8("Initializing: "+g.sg(b)),U8.push(g.mF("yt-remote-cast2-availability-change",function(){g.qF("yt-remote-receiver-availability-change")})),U8.push(g.mF("yt-remote-cast2-receiver-selected",function(){V8(null);
g.qF("yt-remote-auto-connect","cast-selector-receiver")})),U8.push(g.mF("yt-remote-cast2-receiver-resumed",function(){g.qF("yt-remote-receiver-resumed","cast-selector-receiver")})),U8.push(g.mF("yt-remote-cast2-session-change",aAa)),U8.push(g.mF("yt-remote-connection-change",function(a){a?r8(S8(),"YouTube TV"):W8()||(r8(null,null),Hza())})),a=X8(),b.isAuto&&(a.id+="#dial"),g.cE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),T8(" -- with channel params: "+
g.sg(a)),bAa(a),c.start(),S8()||cAa())},fAa=function(){var a=eAa();
o8()&&g.eG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},eAa=function(){var a=R8().Xc.$_gos();
var b=Y8();b&&Z8()&&(Q6(a,b)||a.push(b));return eya(a)},$8=function(){var a=gAa();
!a&&o8()&&Gza()&&(a={key:"cast-selector-receiver",name:Gza()});return a},gAa=function(){var a=eAa(),b=Y8();
b||(b=W8());return g.Ka(a,function(a){return b&&M6(b,a.key)?!0:!1})},Y8=function(){var a=S8();
if(!a)return null;var b=R8().ie();return R6(b,a)},aAa=function(a){T8("remote.onCastSessionChange_: "+N6(a));
if(a){var b=Y8();b&&b.id==a.id?r8(b.id,"YouTube TV"):(b&&a9(),b9(a,1))}else Z8()&&a9()},a9=function(){p8()?m8().stopSession():k8("stopSession called before API ready.");
var a=Z8();a&&(a.disconnect(1),c9(null))},d9=function(){var a=Z8();
return!!a&&3!=a.getProxyState()},T8=function(a){K7("remote",a)},R8=function(){if(!e9){var a=g.x("yt.mdx.remote.screenService_");
e9=a?new O8(a):null}return e9},S8=function(){return g.x("yt.mdx.remote.currentScreenId_")},hAa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},iAa=function(){return g.x("yt.mdx.remote.connectData_")},V8=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},Z8=function(){return g.x("yt.mdx.remote.connection_")},c9=function(a){var b=Z8();
V8(null);a||hAa("");g.va("yt.mdx.remote.connection_",a,void 0);Q8&&((0,g.C)(Q8,function(b){b(a)}),Q8.length=0);
b&&!a?g.qF("yt-remote-connection-change",!1):!b&&a&&g.qF("yt-remote-connection-change",!0)},W8=function(){var a=g.jG();
if(!a)return null;var b=R8().ie();return R6(b,a)},b9=function(a,b){Y8()&&Y8();
hAa(a.id);var c=new H8(P8,a,X8());c.connect(b,iAa());c.subscribe("beforeDisconnect",function(a){g.qF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){Z8()&&c9(null)});
c9(c)},cAa=function(){var a=W8();
a?(T8("Resume connection to: "+N6(a)),b9(a,0)):(W6(),Hza(),T8("Skipping connecting because no session screen found."))},$za=function(){var a=X8();
if(g.Tb(a)){a=U6();var b=g.eG("yt-remote-session-name")||"",c=g.eG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},X8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},bAa=function(a){a?(g.dG("yt-remote-session-app",a.app),g.dG("yt-remote-session-name",a.name)):(g.fG("yt-remote-session-app"),g.fG("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},f9=function(a,b,c){g.M.call(this);
this.F=a;this.l=b;this.o=new g.ZE(this);g.N(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.wP);this.o.O(b,"captionschanged",this.cO);this.o.O(b,"captionssettingschanged",this.yC);this.o.O(b,"videoplayerreset",this.xo);this.o.O(b,"mdxautoplaycancel",this.JG);this.V=this.o.O(b,"onVolumeChange",this.PA);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.cB,this);c.subscribe("remotePlayerChange",this.yl,this);c.subscribe("remoteQueueChange",this.xo,this);c.subscribe("autoplayUpNext",this.yA,
this);c.subscribe("previousNextChange",this.ZA,this);c.subscribe("nowAutoplaying",this.RA,this);c.subscribe("autoplayDismissed",this.xA,this);this.suggestion=null;this.H=new g.YN(64);this.A=new g.Ht(this.uC,500,this);g.N(this,this.A);this.B=new g.Ht(this.vC,1E3,this);g.N(this,this.B);this.K=new d7(this.zT,0,this);g.N(this,this.K);this.C={};this.M=new g.Ht(this.bD,1E3,this);g.N(this,this.M);this.I=new g.Fk(this.YK,1E3,this);g.N(this,this.I);this.N=g.y;this.yC();this.xo();this.yl()},g9=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.P("progresssync",b,d)},jAa=function(a){g9(a,0);
a.A.stop();h9(a,new g.YN(64))},j9=function(a,b){if(i9(a)&&!a.D){var c=null;
b&&(c={style:a.l.ti()},g.ac(c,b));a.g.lC(a.l.ea(1).videoId,c);a.C=B8(a.g).l}},k9=function(a,b){var c=a.l.Xf();
if(c){var d=c.fe();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.uj;var m=B8(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};x8(m,k,l);g.t(b)&&(v8(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);F8(c,"setPlaylist",q);e||D8(c,m);h9(a,new g.YN(1))},kAa=function(a,b){if(b){var c=a.l.yc("captions","tracklist",{gy:1});
c&&c.length?(a.l.Hd("captions","track",b),a.D=!1):(a.l.nl("captions"),a.D=!0)}else a.l.Hd("captions","track",{})},i9=function(a){return B8(a.g).videoId==a.l.ea(1).videoId},h9=function(a,b){a.B.stop();
var c=a.H;if(!g.eO(c,b)){var d=g.V(b,2);d!=g.V(a.H,2)&&g.PT(a.l,d);a.H=b;lAa(a.F,c,b)}},l9=function(a){g.X.call(this,{G:"div",
L:"ytp-remote",J:[{G:"div",L:"ytp-remote-display-status",J:[{G:"div",L:"ytp-remote-display-status-icon",J:[g.KU()]},{G:"div",L:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.gV(this,250);g.N(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);mAa(this,g.MT(a))},mAa=function(a,b){if(3==a.o.Qa()){var c={RECEIVER_NAME:a.o.yc("remote","currentReceiver").name};
c=g.V(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.ob()||g.V(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},m9=function(a,b){g.t_.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},n9=function(a){g.nU.call(this,a);
g.lG({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:P6(),name:g.U("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.YN(64);this.H=0;if(!g.FL(g.W(this.g))){a=
this.g;var b=g.FT(a).H;b&&(b=b.o&&b.o.g)&&(b=new m9(a,b),g.N(this,b));b=new l9(a);g.N(this,b);g.hU(a,b.element,4)}},lAa=function(a,b,c){a.D=c;
a.g.P("presentingplayerstatechange",new g.kO(c,b))},o9=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)a9();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Xf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.dc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.uj,index:Math.max(a.g.xz(),0),currentTime:0==f?void 0:f}}else c=null;T8("Connecting to: "+g.sg(b));"cast-selector-receiver"==b.key?(V8(c||null),p8()?m8().setLaunchParams(c||null):k8("setLaunchParams called before ready.")):!c&&
d9()&&S8()==b.key?g.qF("yt-remote-connection-change",!0):(a9(),V8(c||null),c=R8().ie(),(c=R6(c,b.key))&&b9(c,1))}},Bya={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},n7={"'":"\\'"},nAa={},aya={rV:"atp",K_:"ska",a_:"que",lZ:"mus",G_:"sus"};
K6.prototype.Xm=function(){var a=new K6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var X6,T6="",a7=Y6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",tya=Y6("loadCastFramework")||Y6("loadCastApplicationFramework"),Dza=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(d7,g.M);g.h=d7.prototype;g.h.xH=function(a){this.A=arguments;this.g=!1;this.va?this.o=(0,g.H)()+this.sc:this.va=g.mg(this.B,this.sc)};
g.h.stop=function(){this.va&&(g.ng(this.va),this.va=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();d7.Z.U.call(this)};
g.h.yH=function(){this.o?(this.va=g.mg(this.B,this.o-(0,g.H)()),this.o=null):(this.va=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};e7.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
e7.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=f7.prototype;g.h.ci=null;g.h.vf=!1;g.h.hk=null;g.h.Cu=null;g.h.Nj=null;g.h.kj=null;g.h.hh=null;g.h.Ah=null;g.h.Di=null;g.h.Lc=null;g.h.Ll=0;g.h.wf=null;g.h.np=null;g.h.ih=null;g.h.Mk=-1;g.h.UB=!0;g.h.Oh=!1;g.h.Sq=0;g.h.Fo=null;var zya={},i7={};g.h=f7.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.uS=function(a){a=a.target;var b=this.Fo;b&&3==g.Sw(a)?b.ij():this.hD(a)};
g.h.hD=function(a){try{if(a==this.Lc)a:{var b=g.Sw(this.Lc),c=this.Lc.l,d=this.Lc.getStatus();if(g.rd&&!g.nc(10)||g.td&&!g.mc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Xe&&!g.Ww(this.Lc))break a;this.Oh||4!=b||7==c||(8==c||0>=d?this.g.rf(3):this.g.rf(2));p7(this);var e=this.Lc.getStatus();this.Mk=e;var f=g.Ww(this.Lc);(this.vf=200==e)?(4==b&&l7(this),this.C?(Aya(this,b,f),g.Xe&&this.vf&&3==b&&(this.A.R(this.l,"tick",this.nS),this.l.start())):k7(this,f),this.vf&&!this.Oh&&(4==b?this.g.vo(this):
(this.vf=!1,h7(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.ih=3,j7(13)):(this.ih=0,j7(14)),l7(this),m7(this))}}catch(k){this.Lc&&g.Ww(this.Lc)}finally{}};
g.h.nS=function(){var a=g.Sw(this.Lc),b=g.Ww(this.Lc);this.Ll<b.length&&(p7(this),Aya(this,a,b),this.vf&&4!=a&&h7(this))};
g.h.yR=function(a){o7((0,g.z)(this.xR,this,a),0)};
g.h.xR=function(a){this.Oh||(p7(this),k7(this,a),h7(this))};
g.h.kB=function(a){o7((0,g.z)(this.wR,this,a),0)};
g.h.wR=function(a){this.Oh||(l7(this),this.vf=a,this.g.vo(this),this.g.rf(4))};
g.h.cancel=function(){this.Oh=!0;l7(this)};
g.h.QR=function(){this.hk=null;var a=(0,g.H)();0<=a-this.Cu?(2!=this.kj&&this.g.rf(3),l7(this),this.ih=2,j7(18),m7(this)):Dya(this,this.Cu-a)};g.h=Gya.prototype;g.h.Pq=null;g.h.qe=null;g.h.Go=!1;g.h.wx=null;g.h.mn=null;g.h.Qq=null;g.h.Rq=null;g.h.Ke=null;g.h.wg=-1;g.h.Lk=null;g.h.lk=null;g.h.connect=function(a){this.Rq=a;a=r7(this.g,null,this.Rq);j7(3);this.wx=(0,g.H)();var b=this.g.F;null!=b?(this.Lk=b[0],(this.lk=b[1])?(this.Ke=1,Hya(this)):(this.Ke=2,t7(this))):(J6(a,"MODE","init"),this.qe=new f7(this,void 0,void 0,void 0),this.qe.ci=this.Pq,g7(this.qe,a,!1,null,!0),this.Ke=0)};
g.h.KG=function(a){if(a)this.Ke=2,t7(this);else{j7(4);var b=this.g;b.gf=b.Wg.wg;A7(b,9)}a&&this.rf(2)};
g.h.nq=function(a){return this.g.nq(a)};
g.h.abort=function(){this.qe&&(this.qe.cancel(),this.qe=null);this.wg=-1};
g.h.vx=function(){return!1};
g.h.dB=function(a,b){this.wg=a.Mk;if(0==this.Ke)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.gf=this.wg;A7(c,2);return}this.Lk=c[0];this.lk=c[1]}else c=this.g,c.gf=this.wg,A7(c,2);else if(2==this.Ke)if(this.Go)j7(7),this.Qq=(0,g.H)();else if("11111"==b){if(j7(6),this.Go=!0,this.mn=(0,g.H)(),c=this.mn-this.wx,!g.rd||g.nc(10)||500>c)this.wg=200,this.qe.cancel(),j7(12),s7(this.g,this,!0)}else j7(8),this.mn=this.Qq=(0,g.H)(),this.Go=!1};
g.h.vo=function(){this.wg=this.qe.Mk;if(this.qe.vf)0==this.Ke?this.lk?(this.Ke=1,Hya(this)):(this.Ke=2,t7(this)):2==this.Ke&&((!g.rd||g.nc(10)?!this.Go:200>this.Qq-this.mn)?(j7(11),s7(this.g,this,!1)):(j7(12),s7(this.g,this,!0)));else{0==this.Ke?j7(9):2==this.Ke&&j7(10);var a=this.g;a.gf=this.wg;A7(a,2)}};
g.h.Fl=function(){return this.g.Fl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.rf=function(a){this.g.rf(a)};g.h=u7.prototype;g.h.yk=null;g.h.Pd=null;g.h.oc=null;g.h.Oq=null;g.h.qn=null;g.h.Lv=null;g.h.Gn=null;g.h.ul=0;g.h.vN=0;g.h.kd=null;g.h.Yg=null;g.h.pg=null;g.h.Sh=null;g.h.Wg=null;g.h.mp=null;g.h.wj=-1;g.h.uy=-1;g.h.gf=-1;g.h.cj=0;g.h.Ti=0;g.h.Qh=8;var B7=new g.wf;g.A(Jya,g.Ve);g.A(Kya,g.Ve);g.A(Lya,g.Ve);g.h=u7.prototype;g.h.connect=function(a,b,c,d,e){j7(0);this.Oq=b;this.yk=c||{};d&&g.t(e)&&(this.yk.OSID=d,this.yk.OAID=e);this.C?(o7((0,g.z)(this.jw,this,a),100),Pya(this)):this.jw(a)};
g.h.jw=function(a){this.Wg=new Gya(this);this.Wg.Pq=null;this.Wg.l=this.B;this.Wg.connect(a)};
g.h.vx=function(){return 0==this.g};
g.h.iB=function(a){this.Yg=null;Sya(this,a)};
g.h.hB=function(){this.pg=null;this.oc=new f7(this,this.o,"rpc",this.D);this.oc.ci=null;this.oc.Sq=0;var a=this.Lv.clone();g.rm(a,"RID","rpc");g.rm(a,"SID",this.o);g.rm(a,"CI",this.mp?"0":"1");g.rm(a,"AID",this.wj);v7(this,a);if(!g.rd||g.nc(10))g.rm(a,"TYPE","xmlhttp"),g7(this.oc,a,!0,this.Gn,!1);else{g.rm(a,"TYPE","html");var b=this.oc,c=!!this.Gn;b.kj=3;b.hh=I6(a.clone());Cya(b,c)}};
g.h.dB=function(a,b){if(0!=this.g&&(this.oc==a||this.Pd==a))if(this.gf=a.Mk,this.Pd==a&&3==this.g)if(7<this.Qh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.pg){if(this.oc)if(this.oc.Nj+3E3<this.Pd.Nj)x7(this),this.oc.cancel(),this.oc=null;else break a;z7(this);j7(19)}}else this.uy=c[1],0<this.uy-this.wj&&37500>c[2]&&this.mp&&0==this.Ti&&!this.Sh&&(this.Sh=o7((0,g.z)(this.XN,this),6E3));else A7(this,11)}else b!=nAa.vW.g&&A7(this,11);else if(this.oc==a&&
x7(this),!g.F(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.wj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Gn=e[2],e=e[3],null!=e?this.Qh=e:this.Qh=6,this.g=3,this.kd&&this.kd.Xv(),this.Lv=r7(this,this.Fl()?this.Gn:null,this.Oq),Tya(this)):"stop"==e[0]&&A7(this,7):3==this.g&&("stop"==e[0]?A7(this,7):"noop"!=e[0]&&this.kd&&this.kd.Wv(e),this.Ti=0)}}};
g.h.XN=function(){null!=this.Sh&&(this.Sh=null,this.oc.cancel(),this.oc=null,z7(this),j7(20))};
g.h.vo=function(a){if(this.oc==a){x7(this);this.oc=null;var b=2}else if(this.Pd==a)this.Pd=null,b=1;else return;this.gf=a.Mk;if(0!=this.g)if(a.vf)1==b?(b=(0,g.H)()-a.Nj,B7.dispatchEvent(new Kya(B7,a.Di?a.Di.length:0,b,this.cj)),w7(this),this.A.length=0):Tya(this);else{var c=a.ih,d;if(!(d=3==c||7==c||0==c&&0<this.gf)){if(d=1==b)this.Pd||this.Yg||1==this.g||2<=this.cj?d=!1:(this.Yg=o7((0,g.z)(this.iB,this,a),Uya(this,this.cj)),this.cj++,d=!0);d=!(d||2==b&&z7(this))}if(d)switch(c){case 1:A7(this,5);
break;case 4:A7(this,10);break;case 3:A7(this,6);break;case 7:A7(this,12);break;default:A7(this,2)}}};
g.h.fH=function(a){if(!g.D(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.nT=function(a){a?j7(2):(j7(1),Vya(this,8))};
g.h.nq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Mw;a.F=!1;return a};
g.h.isActive=function(){return!!this.kd&&this.kd.isActive(this)};
g.h.rf=function(a){B7.dispatchEvent(new Lya(B7,a))};
g.h.Fl=function(){return!(!g.rd||g.nc(10))};
g.h=Wya.prototype;g.h.Xv=function(){};
g.h.Wv=function(){};
g.h.Vv=function(){};
g.h.bq=function(){};
g.h.Vw=function(){return{}};
g.h.isActive=function(){return!0};g.A(D7,g.M);D7.prototype.o=function(){500<this.sc&&24E4>2*this.sc&&(this.sc*=2);this.A();this.l&&this.start()};
D7.prototype.start=function(){g.It(this.g,this.sc);this.l=(0,g.H)()+this.sc};
D7.prototype.stop=function(){this.g.stop();this.l=0};
D7.prototype.isActive=function(){return this.g.isActive()};g.A(E7,Wya);g.h=E7.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Jd=function(a){return this.o.Jd(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Te(this.o),Zya(this),g.Te(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new u7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.g;e&&(e.kd=null);d.kd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.wj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ac(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):F7(this)&&Qya(this.g,c)};
g.h.Xv=function(){C7(this.l);this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)Qya(this.g,a[b])}this.P("handlerOpened")};
g.h.Vv=function(a){var b=2==a&&401==this.g.gf;if(4!=a&&!b){if(6==a||410==this.g.gf)b=this.l,b.g.stop(),b.sc=500;this.l.start()}this.P("handlerError",a)};
g.h.bq=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Vw=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.ac(a,this.B);return a};
g.h.Wv=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(C7(this.l),this.l.start(),Oya(this.g)):this.P("handlerMessage",new Xya(a[0],a[1]))};
g.h.XT=function(){this.l.isActive();var a=this.g,b=0;a.oc&&b++;a.Pd&&b++;0!=b?this.l.start():this.connect(this.B,this.A)};G7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
G7.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
G7.prototype.B=function(a){a(Error("request timed out"))};var gza=(0,g.H)(),J7=null,M7=Array(50),L7=-1,N7=!1;g.A(O7,g.bF);O7.prototype.ie=function(){return this.g};
O7.prototype.contains=function(a){return!!Q6(this.g,a)};
O7.prototype.get=function(a){return a?R6(this.g,a):null};
O7.prototype.info=function(a){K7(this.D,a)};g.A(P7,g.bF);var oAa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=P7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.va)&&this.lD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.va)||(g.uD(this.va),this.va=window.NaN)};
g.h.U=function(){this.stop();P7.Z.U.call(this)};
g.h.lD=function(){this.va=window.NaN;this.g=g.ID(H7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,Hb:(0,g.z)(this.aU,this),onError:(0,g.z)(this.ZT,this),nd:(0,g.z)(this.bU,this)})};
g.h.aU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new L6(c))};
g.h.ZT=function(a){this.g=null;a.status&&404==a.status?this.l>=oAa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=oAa[this.l],this.va=g.sD((0,g.z)(this.lD,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.bU=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.A(R7,O7);g.h=R7.prototype;g.h.start=function(){Q7(this)&&this.P("screenChange");!g.eG("yt-remote-lounge-token-expiration")&&kza(this);g.uD(this.l);this.l=g.sD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){Q7(this);hza(this,a);S7(this,!1);this.P("screenChange");b(a);a.token||kza(this)};
g.h.remove=function(a,b){var c=Q7(this);jza(this,a)&&(S7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.ip=function(a,b,c,d){var e=Q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,S7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.U=function(){g.uD(this.l);R7.Z.U.call(this)};
g.h.KH=function(a){Q7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}S7(this,!b);b&&K7(this.D,"Missed "+b+" lounge tokens.")};
g.h.JH=function(a){K7(this.D,"Requesting lounge tokens failed: "+a)};g.A(U7,g.bF);g.h=U7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.eG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.H)()-144E5<a?0:a)?W7(this):(this.A=(0,g.H)()+3E5,g.dG("yt-remote-fast-check-period",this.A),this.Mt())};
g.h.isEmpty=function(){return g.Tb(this.g)};
g.h.update=function(){T7("Updating availability on schedule.");var a=this.C(),b=g.Ib(this.g,function(b,d){return b&&!!R6(a,d)},this);
V7(this,b)};
g.h.U=function(){g.uD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);U7.Z.U.call(this)};
g.h.Mt=function(){g.uD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=nza(this);if(g.Lb(a)){var b=H7(this.B,"/pairing/get_screen_availability");this.l=I7(this.B,b,{lounge_token:g.Nb(a).join(",")},(0,g.z)(this.ZQ,this,a),(0,g.z)(this.YQ,this))}else V7(this,{}),W7(this)};
g.h.ZQ=function(a,b){this.l=null;var c=g.Nb(nza(this));if(g.fb(c,g.Nb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;V7(this,d);W7(this)}else this.Zb("Changing Screen set during request."),this.Mt()};
g.h.YQ=function(a){this.Zb("Screen availability failed: "+a);this.l=null;W7(this)};
g.h.Zb=function(a){K7("OnlineScreenService",a)};g.A(X7,O7);g.h=X7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.ip=function(a,b,c,d){this.o.contains(a)?this.o.ip(a,b,c,d):(a="Updating name of unknown screen: "+a.name,K7(this.D,a),d(Error(a)))};
g.h.ie=function(a){return a?this.g:g.Ua(this.g,(0,g.Gd)(this.A,function(a){return!this.contains(a)},this))};
g.h.mD=function(){return(0,g.Gd)(this.ie(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.nD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new P7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Te(f);d(Y7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Te(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.dU=function(a,b,c,d){g.ID(H7(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,Hb:(0,g.z)(function(a,d){var e=new L6(d.screen||{});if(!e.name||rza(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);rza(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(Y7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
nd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.Te(this.o);g.Te(this.l);X7.Z.U.call(this)};
g.h.aI=function(){sza(this);this.P("screenChange");this.l.update()};
X7.prototype.dispose=X7.prototype.dispose;g.A($7,g.bF);g.h=$7.prototype;g.h.wo=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.oe=function(a){this.ha()||(a&&a8(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){K7(this.M,a)};
g.h.pD=function(){return null};
g.h.Ut=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){a8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Ut("");$7.Z.U.call(this)};g.A(b8,$7);g.h=b8.prototype;g.h.Tt=function(a){if(this.g){if(this.g==a)return;a8(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);uza(this)};
g.h.xj=function(a){this.info("launchWithParams no-op for Cast: "+g.sg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.oe()},this),(0,g.z)(function(){this.oe(Error("Failed to stop receiver app."))},this)):this.oe(Error("Stopping cast device witout session."))};
g.h.Ut=g.y;g.h.U=function(){this.info("disposeInternal");g.uD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;b8.Z.U.call(this)};
g.h.aS=function(a,b){if(!this.ha())if(b){var c=g.Gw(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.sg(c));switch(d){case "mdxSessionStatus":tza(this,c.screenId);break;default:a8(this,"Unknown youtube message: "+d)}}else a8(this,"Unable to parse message.")}else a8(this,"No data in message.")};
g.h.kx=function(a,b,c,d){qza(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(a8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.sD((0,g.z)(this.kx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.pD=function(){return this.g};
g.h.eU=function(a){this.ha()||a||(a8(this,"Cast session died."),this.oe())};g.A(c8,$7);g.h=c8.prototype;g.h.Tt=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.xj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.uD(this.C);this.A?this.A.stop((0,g.z)(this.oe,this,null),(0,g.z)(this.oe,this,"Failed to stop DIAL device.")):this.oe()};
g.h.U=function(){this.g();this.g=g.y;g.uD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;c8.Z.U.call(this)};
g.h.hU=function(a){this.ha()||a||(a8(this,"DIAL session died."),this.g(),this.g=g.y,this.oe())};
g.h.Dr=function(a){this.I=P6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,wza(this));a(b);vza(this)}else this.D=(0,g.z)(function(){g.uD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,wza(this));a(b);vza(this)},this),this.C=g.sD((0,g.z)(function(){this.D()},this),100)};
g.h.rJ=function(a,b,c){qza(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.wo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Dr(b,c)},this),(0,g.z)(function(a){a8(this,"Failed to get DIAL screen: "+a);
this.Dr(b,c)},this))};g.A(d8,$7);d8.prototype.stop=function(){this.oe()};
d8.prototype.Tt=g.y;d8.prototype.xj=function(){g.uD(this.g);this.g=window.NaN;var a=R6(this.H.ie(),this.l.label);a?this.wo(a):this.oe(Error("No such screen"))};
d8.prototype.U=function(){g.uD(this.g);this.g=window.NaN;d8.Z.U.call(this)};g.A(e8,g.bF);g.h=e8.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.eB,this),(0,g.z)(this.KQ,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.IO,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),dza(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.oD,this)),this.o=yza(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.Zb("Failed to set initial custom receivers: "+g.sg(a))},this)),this.P("yt-remote-cast2-availability-change",g8(this)),b(!0))},this),(0,g.z)(function(a){this.Zb("Failed to initialize API: "+g.sg(a));
b(!1)},this))};
g.h.XS=function(a,b){f8("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)f8("Unsetting old screen status: "+this.g.l.friendlyName),h8(this,null)}if(a&&b){if(!this.g){c=R6(this.l.ie(),a);if(!c){f8("setConnectedScreenStatus: Unknown screen.");return}var d=xza(this,c);d||(f8("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.Zb("Failed to set initial custom receivers: "+g.sg(a))},this)));
f8("setConnectedScreenStatus: new active receiver: "+d.friendlyName);h8(this,new d8(this.l,d),!0)}this.g.Ut(b)}else f8("setConnectedScreenStatus: no screen.")};
g.h.YS=function(a){this.ha()?this.Zb("Setting connection data on disposed cast v2"):this.g?this.g.xj(a):this.Zb("Setting connection data without a session")};
g.h.gU=function(){this.ha()?this.Zb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),h8(this,null)):f8("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.eB,this),(0,g.z)(this.dR,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.oD,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Sa(g.x("yt.mdx.remote.debug.handlers_")||[],aza);g.Te(this.g);e8.Z.U.call(this)};
g.h.Zb=function(a){K7("Controller",a)};
g.h.fB=function(a,b){this.g==a&&(b||h8(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.GQ=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),f8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)f8("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{f8("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:h8(this,
new d8(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:h8(this,new c8(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:h8(this,new b8(this.l,a));break;default:this.Zb("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.Zb("Stopping receiver w/o session: "+a.friendlyName)}else this.Zb("onReceiverAction_ called without receiver.")};
g.h.IO=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Zb("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.Zb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return f8("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Zb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);h8(this,new c8(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.rJ,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.Dr,b))};
g.h.eB=function(a){if(!this.ha()){f8("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)f8("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),h8(this,new b8(this.l,b),!0);else{this.Zb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=R6(this.l.ie(),c.label);
d&&M6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(f8("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Te(this.g),this.g=new b8(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.fB,this,this.g)),this.g.xj(null));this.g.Tt(a)}}};
g.h.fU=function(){return this.g?this.g.pD():null};
g.h.dR=function(a){this.ha()||(this.Zb("Failed to estabilish a session: "+g.sg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&h8(this,null))};
g.h.KQ=function(a){f8("Receiver availability updated: "+a);if(!this.ha()){var b=g8(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;g8(this)!=b&&this.P("yt-remote-cast2-availability-change",g8(this))}};
g.h.oD=function(){this.ha()||(this.o=yza(this),f8("Updating custom receivers: "+g.sg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.Zb("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",g8(this)))};
e8.prototype.setLaunchParams=e8.prototype.YS;e8.prototype.setConnectedScreenStatus=e8.prototype.XS;e8.prototype.stopSession=e8.prototype.gU;e8.prototype.getCastSession=e8.prototype.fU;e8.prototype.requestSession=e8.prototype.requestSession;e8.prototype.init=e8.prototype.init;e8.prototype.dispose=e8.prototype.dispose;var n8=[];s8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";t8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Kf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
s8.prototype.ob=function(){return 1==this.g};
s8.prototype.getDuration=function(){return this.C?this.H+u8(this):this.H};
s8.prototype.clone=function(){return new s8(y8(this))};g.A(A8,g.bF);g.h=A8.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,G8(this,"play")):F8(this,"play"),E8(this,1,w8(B8(this))),this.P("remotePlayerChange")):C8(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,G8(this,"pause")):F8(this,"pause"),E8(this,2,w8(B8(this))),this.P("remotePlayerChange")):C8(this,this.pause)};
g.h.kD=function(a){if(1==this.g){if(this.l){var b=B8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.ob()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,G8(this,"seekTo",{newTime:a}))}else F8(this,"seekTo",{newTime:a});E8(this,3,a);this.P("remotePlayerChange")}else C8(this,g.Ea(this.kD,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,G8(this,"stopVideo")):F8(this,"stopVideo");var a=B8(this);a.index=-1;a.videoId="";t8(a);D8(this,a);this.P("remotePlayerChange")}else C8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=B8(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){K7("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Zb("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){K7("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Zb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);F8(this,"setVolume",e)}c.muted=b;c.volume=a;D8(this,c)}else C8(this,g.Ea(this.setVolume,a,b))};
g.h.lC=function(a,b){if(1==this.g){var c=B8(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.sg(b.style),g.ac(d,c.l));F8(this,"setSubtitlesTrack",d);D8(this,c)}else C8(this,g.Ea(this.lC,a,b))};
g.h.Hu=function(a,b){if(1==this.g){F8(this,"setAudioTrack",{videoId:a,audioTrackId:b.wc.id});var c=B8(this);c.audioTrackId=b.wc.id;D8(this,c)}else C8(this,g.Ea(this.Hu,a,b))};
g.h.jD=function(a,b){if(1==this.g){if(a&&b){var c=B8(this);x8(c,a,b);D8(this,c)}F8(this,"previous")}else C8(this,g.Ea(this.jD,a,b))};
g.h.iD=function(a,b){if(1==this.g){if(a&&b){var c=B8(this);x8(c,a,b);D8(this,c)}F8(this,"next")}else C8(this,g.Ea(this.iD,a,b))};
g.h.Bw=function(){1==this.g?F8(this,"dismissAutoplay"):C8(this,this.Bw)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}A8.Z.dispose.call(this)};
g.h.U=function(){Lza(this);this.A=null;this.B.clear();z8(this,null);A8.Z.U.call(this)};
g.h.Iu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.RB(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.CQ=function(a,b){this.P(a,b)};
g.h.eO=function(a){if(!a)this.wl(null),z8(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=B8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)K7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,D8(this,b)}};
g.h.wl=function(a){K7("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),Mza(this),this.P("remotePlayerChange")};
g.h.dO=function(a){a?(Mza(this),this.P("remotePlayerChange")):this.wl(null)};
g.h.rO=function(){var a=Iza();a&&z8(this,a)};
g.h.Zb=function(a){K7("CP",a)};g.A(H8,g.bF);g.h=H8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.bb.listId=c);this.bb.videoId=d;this.bb.index=k||0;this.bb.state=3;v8(this.bb,m);this.A="UNSUPPORTED";I8("Connecting with setPlaylist and params: "+g.sg(l));this.g.connect({method:"setPlaylist",params:g.sg(l)},a,hya())}else I8("Connecting without params"),
this.g.connect({},a,hya());Oza(this)};
g.h.dispose=function(){this.ha()||(this.P("beforeDispose"),J8(this,3));H8.Z.dispose.call(this)};
g.h.U=function(){K8(this);M8(this);L8(this);g.uD(this.H);this.H=window.NaN;g.uD(this.I);this.I=window.NaN;this.o=null;g.NE(this.V);this.V.length=0;this.g.dispose();H8.Z.U.call(this);this.A=this.D=this.l=this.bb=this.g=null};
g.h.BH=function(){this.C(2)};
g.h.iO=function(){I8("Channel opened");this.N&&(this.N=!1,L8(this),this.M=g.sD((0,g.z)(function(){I8("Timing out waiting for a screen.");this.C(1)},this),15E3));
lya(Yya(this.g),this.X)};
g.h.fO=function(){I8("Channel closed");(0,window.isNaN)(this.B)?W6(!0):W6();this.dispose()};
g.h.gO=function(a){W6();(0,window.isNaN)(this.F())?(I8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,I8("Channel error: "+a+" with reconnection in "+this.F()+" ms"),J8(this,2))};
g.h.hO=function(a){a.params?I8("Received: action="+a.action+", params="+g.sg(a.params)):I8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Gw(a.params.devices);this.l=(0,g.I)(a,function(a){return new K6(a)});
a=!!g.Ka(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
Rza(this,a);break;case "loungeScreenDisconnected":g.Ta(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
Rza(this,!1);break;case "remoteConnected":var b=new K6(g.Gw(a.params.device));g.Ka(this.l,function(a){return b?a.id==b.id:!1})||g.Qa(this.l,b);
break;case "remoteDisconnected":b=new K6(g.Gw(a.params.device));g.Ta(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Tza(this,a);break;case "nowPlaying":Vza(this,a);break;case "onStateChange":Uza(this,a);break;case "onAdStateChange":Wza(this,a);break;case "onVolumeChanged":Xza(this,a);break;case "onSubtitlesTrackChanged":Sza(this,a);break;case "nowAutoplaying":Yza(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.P("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":Zza(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:I8("Unrecognized action: "+a.action)}};
g.h.GS=function(){if(this.o){var a=this.o;this.o=null;this.bb.videoId!=a&&N8(this,"getNowPlaying")}};
H8.prototype.subscribe=H8.prototype.subscribe;H8.prototype.unsubscribeByKey=H8.prototype.Jd;H8.prototype.da=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?F7(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
H8.prototype.getProxyState=H8.prototype.da;H8.prototype.C=function(a){I8("Disconnecting with "+a);K8(this);this.P("beforeDisconnect",a);1==a&&W6();Zya(this.g,a);this.dispose()};
H8.prototype.disconnect=H8.prototype.C;H8.prototype.ca=function(){var a=this.bb;this.o&&(a=this.bb.clone(),x8(a,this.o,a.index));return y8(a)};
H8.prototype.getPlayerContextData=H8.prototype.ca;
H8.prototype.la=function(a){var b=new s8(a);b.videoId&&b.videoId!=this.bb.videoId&&(this.o=b.videoId,g.uD(this.H),this.H=g.sD((0,g.z)(this.GS,this),5E3));var c=[];this.bb.listId==b.listId&&this.bb.videoId==b.videoId&&this.bb.index==b.index||c.push("remoteQueueChange");this.bb.g==b.g&&this.bb.volume==b.volume&&this.bb.muted==b.muted&&w8(this.bb)==w8(b)&&g.sg(this.bb.l)==g.sg(b.l)||c.push("remotePlayerChange");this.bb.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
H8.prototype.setPlayerContextData=H8.prototype.la;H8.prototype.W=function(){var a=this.g.C.id,b=g.Ka(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
H8.prototype.getOtherConnectedRemoteId=H8.prototype.W;H8.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.H)():window.NaN};
H8.prototype.getReconnectTimeout=H8.prototype.F;H8.prototype.Y=function(){return this.A||"UNSUPPORTED"};
H8.prototype.getAutoplayMode=H8.prototype.Y;H8.prototype.ba=function(){return this.D||""};
H8.prototype.getAutoplayVideoId=H8.prototype.ba;H8.prototype.oa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Jt(a.g);a.start()}};
H8.prototype.reconnect=H8.prototype.oa;H8.prototype.fa=function(a,b){N8(this,a,b);Qza(this)};
H8.prototype.sendMessage=H8.prototype.fa;g.A(O8,O7);g.h=O8.prototype;g.h.ie=function(a){return this.Xc.$_gs(a)};
g.h.contains=function(a){return!!this.Xc.$_c(a)};
g.h.get=function(a){return this.Xc.$_g(a)};
g.h.start=function(){this.Xc.$_st()};
g.h.add=function(a,b,c){this.Xc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Xc.$_r(a,b,c)};
g.h.ip=function(a,b,c,d){this.Xc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.Xc.$_ubk(this.l[a]);this.l.length=0;this.Xc=null;O8.Z.U.call(this)};
g.h.cU=function(){this.P("screenChange")};
g.h.dQ=function(){this.P("onlineScreenChange")};
X7.prototype.$_st=X7.prototype.start;X7.prototype.$_gspc=X7.prototype.dU;X7.prototype.$_gsppc=X7.prototype.nD;X7.prototype.$_c=X7.prototype.contains;X7.prototype.$_g=X7.prototype.get;X7.prototype.$_a=X7.prototype.add;X7.prototype.$_un=X7.prototype.ip;X7.prototype.$_r=X7.prototype.remove;X7.prototype.$_gs=X7.prototype.ie;X7.prototype.$_gos=X7.prototype.mD;X7.prototype.$_s=X7.prototype.subscribe;X7.prototype.$_ubk=X7.prototype.Jd;var P8=null,Q8=null,e9=null,U8=[];g.p(f9,g.M);g.h=f9.prototype;
g.h.U=function(){g.M.prototype.U.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.cB,this);this.g.unsubscribe("remotePlayerChange",this.yl,this);this.g.unsubscribe("remoteQueueChange",this.xo,this);this.g.unsubscribe("autoplayUpNext",this.yA,this);this.g.unsubscribe("previousNextChange",this.ZA,this);this.g.unsubscribe("nowAutoplaying",this.RA,this);this.g.unsubscribe("autoplayDismissed",this.xA,this);this.g=this.F=null};
g.h.jz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(i9(this)){if(1081!=B8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":B8(this.g).ob()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.ij(c[0],c[1]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.Hu(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();k9(this,0==c?void 0:c);break;case "control_seek":k9(this,c[0]);break;case "control_subtitles_set_track":j9(this,c[0]);break;case "control_set_audio_track":c=c[0],i9(this)&&this.g.Hu(this.l.ea(1).videoId,c)}};
g.h.cO=function(a){this.K.xH(a)};
g.h.zT=function(a){this.jz("control_subtitles_set_track",g.Tb(a)?null:a)};
g.h.yC=function(){var a=this.l.yc("captions","track");g.Tb(a)||j9(this,a)};
g.h.PA=function(a){if(i9(this)){this.g.unsubscribe("remotePlayerChange",this.yl,this);var b=Math.round(a.volume);a=!!a.muted;var c=B8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.M.start();this.g.subscribe("remotePlayerChange",this.yl,this)}};
g.h.wP=function(){g.Tb(this.C)||kAa(this,this.C);this.D=!1};
g.h.cB=function(a,b){this.B.stop();2==b&&this.vC()};
g.h.yl=function(){if(i9(this)){this.A.stop();var a=B8(this.g);switch(a.g){case 1081:case 1:h9(this,new g.YN(8));this.uC();break;case 1085:case 3:h9(this,new g.YN(9));break;case 1083:case 0:h9(this,new g.YN(2));this.I.stop();g9(this,this.l.ea().lengthSeconds);break;case 1084:h9(this,new g.YN(4));break;case 2:h9(this,new g.YN(4));g9(this,w8(a));break;case -1:h9(this,new g.YN(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},h9(this,new g.YN(128,a))}a=B8(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,kAa(this,a));a=B8(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.M.isActive()||this.bD()}else jAa(this)};
g.h.ZA=function(){this.l.P("mdxpreviousnextchange")};
g.h.xo=function(){i9(this)||jAa(this)};
g.h.JG=function(){this.g.Bw()};
g.h.yA=function(a){a&&(a=g.ID("/watch_queue_ajax",{method:"GET",Tc:{action_get_watch_queue_item:1,video_id:a},Hb:(0,g.z)(this.CR,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.CR=function(a,b){var c=new g.ZM({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.RA=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.xA=function(){this.l.P("mdxautoplaycanceled")};
g.h.YK=function(a,b){-1==B8(this.g).g?k9(this,a):b&&this.g.kD(a)};
g.h.bD=function(){if(i9(this)){var a=B8(this.g);this.o.Ca(this.V);a.muted?this.l.mute():this.l.Yf();this.l.setVolume(a.volume);this.V=this.o.O(this.l,"onVolumeChange",this.PA)}};
g.h.uC=function(){this.A.stop();if(!this.g.ha()){var a=B8(this.g);a.ob()&&h9(this,new g.YN(8));g9(this,w8(a));this.A.start()}};
g.h.vC=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(l9,g.X);l9.prototype.A=function(a){mAa(this,a.state)};g.p(m9,g.t_);m9.prototype.I=function(){var a=this.l.yc("remote","receivers");a&&1<a.length&&!this.l.yc("remote","quickCast")?(this.F=g.ib(a,this.B,this),g.u_(this,(0,g.I)(a,this.B)),a=this.l.yc("remote","currentReceiver"),this.qf(this.B(a)),this.enable(!0)):this.enable(!1)};
m9.prototype.B=function(a){return a.key};
m9.prototype.pf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
m9.prototype.md=function(a){g.t_.prototype.md.call(this,a);this.l.Hd("remote","currentReceiver",this.F[a]);this.A.Nb()};g.p(n9,g.nU);g.h=n9.prototype;g.h.create=function(){dAa(g.uL(g.W(this.g)));this.C.push(g.mF("yt-remote-before-disconnect",this.YN,this));this.C.push(g.mF("yt-remote-connection-change",this.LQ,this));this.C.push(g.mF("yt-remote-receiver-availability-change",this.aB,this));this.C.push(g.mF("yt-remote-auto-connect",this.JQ,this));this.C.push(g.mF("yt-remote-receiver-resumed",this.IQ,this));this.aB()};
g.h.load=function(){this.g.Is();g.nU.prototype.load.call(this);this.B=new f9(this,this.g,this.l);var a=(a=iAa())?a.currentTime:0;var b=d9()?new A8(Z8(),void 0):null;0==a&&b&&(a=w8(B8(b)));0!=a&&(this.H=a||0,this.g.P("progresssync",a,void 0));lAa(this,this.D,this.D);g.D0(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.Ue(this.B,this.l);this.l=this.B=null;g.nU.prototype.unload.call(this);g.D0(this.g.app,5)};
g.h.U=function(){g.nF(this.C);g.nU.prototype.U.call(this)};
g.h.dl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.jz.apply(this.B,[].concat([a],g.qa(c)))};
g.h.tH=function(){return this.loaded?this.B.suggestion:null};
g.h.Kf=function(){return this.l?B8(this.l).Kf:!1};
g.h.hasNext=function(){return this.l?B8(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.zK=function(){var a=B8(this.l),b=this.g.ea();return{allowSeeking:this.g.Yc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+u8(a):a.A,isPeggedToLive:1>=(a.C?a.o+u8(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+u8(a):a.o,seekableStart:0<a.B?a.B+u8(a):a.B}};
g.h.AK=function(){this.l&&this.l.iD()};
g.h.BK=function(){this.l&&this.l.jD()};
g.h.YN=function(a){1==a&&(this.I=this.l?B8(this.l):null)};
g.h.LQ=function(){var a=d9()?new A8(Z8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Te(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.vz(a.videoId,w8(a)));this.g.P("videodatachange","newdata",this.g.ea(),3)};
g.h.aB=function(){this.F=[this.o].concat(fAa());var a=$8()||this.o;o9(this,a);this.g.ra("onMdxReceiversChange")};
g.h.JQ=function(){var a=$8();o9(this,a)};
g.h.IQ=function(){this.A=$8()};
g.h.yK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?q8():o9(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&q8(),!0):!1}};
g.h.CK=function(){F8(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.rd=function(){return!1};g.$_.remote=n9;})(_yt_player);
